// Generated by CIRCT unknown git version
// Standard header to adapt well known macros to our needs.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

module TLXbar(
  input         clock,
                reset,
                auto_in_1_a_valid,
  input  [2:0]  auto_in_1_a_bits_opcode,
                auto_in_1_a_bits_param,
  input  [3:0]  auto_in_1_a_bits_size,
  input         auto_in_1_a_bits_source,
  input  [31:0] auto_in_1_a_bits_address,
  input         auto_in_1_a_bits_user_amba_prot_bufferable,
                auto_in_1_a_bits_user_amba_prot_modifiable,
                auto_in_1_a_bits_user_amba_prot_readalloc,
                auto_in_1_a_bits_user_amba_prot_writealloc,
                auto_in_1_a_bits_user_amba_prot_privileged,
                auto_in_1_a_bits_user_amba_prot_secure,
                auto_in_1_a_bits_user_amba_prot_fetch,
  input  [3:0]  auto_in_1_a_bits_mask,
  input  [31:0] auto_in_1_a_bits_data,
  input         auto_in_1_a_bits_corrupt,
                auto_in_1_d_ready,
                auto_in_0_a_valid,
  input  [2:0]  auto_in_0_a_bits_opcode,
                auto_in_0_a_bits_param,
  input  [3:0]  auto_in_0_a_bits_size,
                auto_in_0_a_bits_source,
  input  [31:0] auto_in_0_a_bits_address,
  input  [3:0]  auto_in_0_a_bits_mask,
  input  [31:0] auto_in_0_a_bits_data,
  input         auto_in_0_a_bits_corrupt,
                auto_in_0_d_ready,
                auto_out_1_a_ready,
                auto_out_1_d_valid,
  input  [2:0]  auto_out_1_d_bits_opcode,
  input  [1:0]  auto_out_1_d_bits_param,
  input  [2:0]  auto_out_1_d_bits_size,
  input  [4:0]  auto_out_1_d_bits_source,
  input  [1:0]  auto_out_1_d_bits_sink,
  input         auto_out_1_d_bits_denied,
  input  [31:0] auto_out_1_d_bits_data,
  input         auto_out_1_d_bits_corrupt,
                auto_out_0_a_ready,
                auto_out_0_d_valid,
  input  [2:0]  auto_out_0_d_bits_opcode,
  input  [1:0]  auto_out_0_d_bits_param,
  input  [3:0]  auto_out_0_d_bits_size,
  input  [4:0]  auto_out_0_d_bits_source,
  input         auto_out_0_d_bits_sink,
                auto_out_0_d_bits_denied,
  input  [31:0] auto_out_0_d_bits_data,
  input         auto_out_0_d_bits_corrupt,
  output        auto_in_1_a_ready,
                auto_in_1_d_valid,
  output [2:0]  auto_in_1_d_bits_opcode,
  output [1:0]  auto_in_1_d_bits_param,
  output [3:0]  auto_in_1_d_bits_size,
  output        auto_in_1_d_bits_source,
  output [1:0]  auto_in_1_d_bits_sink,
  output        auto_in_1_d_bits_denied,
  output [31:0] auto_in_1_d_bits_data,
  output        auto_in_1_d_bits_corrupt,
                auto_in_0_a_ready,
                auto_in_0_d_valid,
  output [2:0]  auto_in_0_d_bits_opcode,
  output [1:0]  auto_in_0_d_bits_param,
  output [3:0]  auto_in_0_d_bits_size,
                auto_in_0_d_bits_source,
  output [1:0]  auto_in_0_d_bits_sink,
  output        auto_in_0_d_bits_denied,
  output [31:0] auto_in_0_d_bits_data,
  output        auto_in_0_d_bits_corrupt,
                auto_out_1_a_valid,
  output [2:0]  auto_out_1_a_bits_opcode,
                auto_out_1_a_bits_size,
  output [4:0]  auto_out_1_a_bits_source,
  output [31:0] auto_out_1_a_bits_address,
  output        auto_out_1_a_bits_user_amba_prot_bufferable,
                auto_out_1_a_bits_user_amba_prot_modifiable,
                auto_out_1_a_bits_user_amba_prot_readalloc,
                auto_out_1_a_bits_user_amba_prot_writealloc,
                auto_out_1_a_bits_user_amba_prot_privileged,
                auto_out_1_a_bits_user_amba_prot_secure,
                auto_out_1_a_bits_user_amba_prot_fetch,
  output [3:0]  auto_out_1_a_bits_mask,
  output [31:0] auto_out_1_a_bits_data,
  output        auto_out_1_d_ready,
                auto_out_0_a_valid,
  output [2:0]  auto_out_0_a_bits_opcode,
                auto_out_0_a_bits_param,
  output [3:0]  auto_out_0_a_bits_size,
  output [4:0]  auto_out_0_a_bits_source,
  output [31:0] auto_out_0_a_bits_address,
  output [3:0]  auto_out_0_a_bits_mask,
  output [31:0] auto_out_0_a_bits_data,
  output        auto_out_0_a_bits_corrupt,
                auto_out_0_d_ready
);

  wire        allowed_3_1;	// @[Arbiter.scala:122:24]
  wire        allowed_3_0;	// @[Arbiter.scala:122:24]
  wire        allowed_2_1;	// @[Arbiter.scala:122:24]
  wire        allowed_2_0;	// @[Arbiter.scala:122:24]
  wire        allowed_1_1;	// @[Arbiter.scala:122:24]
  wire        allowed_1_0;	// @[Arbiter.scala:122:24]
  wire        allowed_1;	// @[Arbiter.scala:122:24]
  wire        allowed_0;	// @[Arbiter.scala:122:24]
  wire [4:0]  portsAOI_filtered_1_bits_source = {1'h0, auto_in_0_a_bits_source};	// @[Bundle_ACancel.scala:56:22, Xbar.scala:240:29]
  wire [4:0]  portsAOI_filtered_1_1_bits_source = {4'h8, auto_in_1_a_bits_source};	// @[Parameters.scala:54:32, Xbar.scala:240:55]
  wire [1:0]  out_12_bits_sink = {1'h0, auto_out_0_d_bits_sink};	// @[Bundle_ACancel.scala:56:22, Xbar.scala:326:28]
  wire [3:0]  out_13_bits_size = {1'h0, auto_out_1_d_bits_size};	// @[BundleMap.scala:247:19, Bundle_ACancel.scala:56:22]
  wire [3:0]  _GEN = auto_in_0_a_bits_address[31:28] ^ 4'h9;	// @[Parameters.scala:137:31]
  wire        requestAIO_0_0 = {auto_in_0_a_bits_address[31], auto_in_0_a_bits_address[28]} == 2'h0 | {_GEN[3], _GEN[0], auto_in_0_a_bits_address[26]} == 3'h0;	// @[Bundles.scala:259:74, Parameters.scala:137:{31,45,65}, Xbar.scala:366:92]
  wire        requestAIO_0_1 = {~(auto_in_0_a_bits_address[31]), auto_in_0_a_bits_address[28]} == 2'h0;	// @[Bundles.scala:259:74, Parameters.scala:137:{31,45,65}]
  wire [3:0]  _GEN_0 = auto_in_1_a_bits_address[31:28] ^ 4'h9;	// @[Parameters.scala:137:31]
  wire        requestAIO_1_0 = {auto_in_1_a_bits_address[31], auto_in_1_a_bits_address[28]} == 2'h0 | {_GEN_0[3], _GEN_0[0], auto_in_1_a_bits_address[26]} == 3'h0;	// @[Bundles.scala:259:74, Parameters.scala:137:{31,45,65}, Xbar.scala:366:92]
  wire        requestAIO_1_1 = {~(auto_in_1_a_bits_address[31]), auto_in_1_a_bits_address[28]} == 2'h0;	// @[Bundles.scala:259:74, Parameters.scala:137:{31,45,65}]
  wire        requestDOI_0_1 = auto_out_0_d_bits_source[4:1] == 4'h8;	// @[Parameters.scala:54:{10,32}]
  wire        requestDOI_1_1 = auto_out_1_d_bits_source[4:1] == 4'h8;	// @[Parameters.scala:54:{10,32}]
  wire        portsAOI_filtered_0_earlyValid = auto_in_0_a_valid & requestAIO_0_0;	// @[Xbar.scala:366:92, :431:50]
  wire        portsAOI_filtered_1_earlyValid = auto_in_0_a_valid & requestAIO_0_1;	// @[Parameters.scala:137:65, Xbar.scala:431:50]
  wire        portsAOI_filtered_1_0_earlyValid = auto_in_1_a_valid & requestAIO_1_0;	// @[Xbar.scala:366:92, :431:50]
  wire        portsAOI_filtered_1_1_earlyValid = auto_in_1_a_valid & requestAIO_1_1;	// @[Parameters.scala:137:65, Xbar.scala:431:50]
  wire        out_8_earlyValid = auto_out_0_d_valid & ~(auto_out_0_d_bits_source[4]);	// @[Parameters.scala:54:{10,32}, Xbar.scala:182:40]
  wire        out_12_earlyValid = auto_out_0_d_valid & requestDOI_0_1;	// @[Parameters.scala:54:32, Xbar.scala:182:40]
  wire        out_9_earlyValid = auto_out_1_d_valid & ~(auto_out_1_d_bits_source[4]);	// @[Parameters.scala:54:{10,32}, Xbar.scala:182:40]
  wire        out_13_earlyValid = auto_out_1_d_valid & requestDOI_1_1;	// @[Parameters.scala:54:32, Xbar.scala:182:40]
  reg  [9:0]  beatsLeft;	// @[Arbiter.scala:88:30]
  wire        idle = beatsLeft == 10'h0;	// @[Arbiter.scala:88:30, :89:28, Edges.scala:221:14]
  wire [1:0]  readys_valid = {portsAOI_filtered_1_0_earlyValid, portsAOI_filtered_0_earlyValid};	// @[Cat.scala:33:92, Xbar.scala:431:50]
  reg  [1:0]  readys_mask;	// @[Arbiter.scala:24:23]
  wire [1:0]  _readys_filter_T_1 = readys_valid & ~readys_mask;	// @[Arbiter.scala:24:23, :25:{28,30}, Cat.scala:33:92]
  wire [1:0]  readys_readys = ~({readys_mask[1], _readys_filter_T_1[1] | readys_mask[0]} & {|_readys_filter_T_1, portsAOI_filtered_1_0_earlyValid | _readys_filter_T_1[0]});	// @[Arbiter.scala:24:23, :25:28, :26:58, :27:{18,29,39,48}, Xbar.scala:431:50, package.scala:254:43]
  wire        earlyWinner_0 = readys_readys[0] & portsAOI_filtered_0_earlyValid;	// @[Arbiter.scala:27:18, :96:86, :98:79, Xbar.scala:431:50]
  wire        earlyWinner_1 = readys_readys[1] & portsAOI_filtered_1_0_earlyValid;	// @[Arbiter.scala:27:18, :96:86, :98:79, Xbar.scala:431:50]
  wire        _out_0_a_earlyValid_T = portsAOI_filtered_0_earlyValid | portsAOI_filtered_1_0_earlyValid;	// @[Arbiter.scala:108:36, Xbar.scala:431:50]
  reg         state_0;	// @[Arbiter.scala:117:26]
  reg         state_1;	// @[Arbiter.scala:117:26]
  wire        muxStateEarly_0 = idle ? earlyWinner_0 : state_0;	// @[Arbiter.scala:89:28, :98:79, :117:26, :118:30]
  wire        muxStateEarly_1 = idle ? earlyWinner_1 : state_1;	// @[Arbiter.scala:89:28, :98:79, :117:26, :118:30]
  assign allowed_0 = idle ? readys_readys[0] : state_0;	// @[Arbiter.scala:27:18, :89:28, :96:86, :117:26, :122:24]
  assign allowed_1 = idle ? readys_readys[1] : state_1;	// @[Arbiter.scala:27:18, :89:28, :96:86, :117:26, :122:24]
  wire        x1_out_1_valid = idle ? _out_0_a_earlyValid_T : state_0 & portsAOI_filtered_0_earlyValid | state_1 & portsAOI_filtered_1_0_earlyValid;	// @[Arbiter.scala:89:28, :108:36, :117:26, :126:29, Mux.scala:27:73, Xbar.scala:431:50]
  reg  [9:0]  beatsLeft_1;	// @[Arbiter.scala:88:30]
  wire        idle_1 = beatsLeft_1 == 10'h0;	// @[Arbiter.scala:88:30, :89:28, Edges.scala:221:14]
  wire [1:0]  readys_valid_1 = {portsAOI_filtered_1_1_earlyValid, portsAOI_filtered_1_earlyValid};	// @[Cat.scala:33:92, Xbar.scala:431:50]
  reg  [1:0]  readys_mask_1;	// @[Arbiter.scala:24:23]
  wire [1:0]  _readys_filter_T_3 = readys_valid_1 & ~readys_mask_1;	// @[Arbiter.scala:24:23, :25:{28,30}, Cat.scala:33:92]
  wire [1:0]  readys_readys_1 = ~({readys_mask_1[1], _readys_filter_T_3[1] | readys_mask_1[0]} & {|_readys_filter_T_3, portsAOI_filtered_1_1_earlyValid | _readys_filter_T_3[0]});	// @[Arbiter.scala:24:23, :25:28, :26:58, :27:{18,29,39,48}, Xbar.scala:431:50, package.scala:254:43]
  wire        earlyWinner_1_0 = readys_readys_1[0] & portsAOI_filtered_1_earlyValid;	// @[Arbiter.scala:27:18, :96:86, :98:79, Xbar.scala:431:50]
  wire        earlyWinner_1_1 = readys_readys_1[1] & portsAOI_filtered_1_1_earlyValid;	// @[Arbiter.scala:27:18, :96:86, :98:79, Xbar.scala:431:50]
  wire        _out_1_a_earlyValid_T = portsAOI_filtered_1_earlyValid | portsAOI_filtered_1_1_earlyValid;	// @[Arbiter.scala:108:36, Xbar.scala:431:50]
  reg         state_1_0;	// @[Arbiter.scala:117:26]
  reg         state_1_1;	// @[Arbiter.scala:117:26]
  wire        muxStateEarly_1_0 = idle_1 ? earlyWinner_1_0 : state_1_0;	// @[Arbiter.scala:89:28, :98:79, :117:26, :118:30]
  wire        muxStateEarly_1_1 = idle_1 ? earlyWinner_1_1 : state_1_1;	// @[Arbiter.scala:89:28, :98:79, :117:26, :118:30]
  assign allowed_1_0 = idle_1 ? readys_readys_1[0] : state_1_0;	// @[Arbiter.scala:27:18, :89:28, :96:86, :117:26, :122:24]
  assign allowed_1_1 = idle_1 ? readys_readys_1[1] : state_1_1;	// @[Arbiter.scala:27:18, :89:28, :96:86, :117:26, :122:24]
  wire        bundleOut_1_out_1_valid = idle_1 ? _out_1_a_earlyValid_T : state_1_0 & portsAOI_filtered_1_earlyValid | state_1_1 & portsAOI_filtered_1_1_earlyValid;	// @[Arbiter.scala:89:28, :108:36, :117:26, :126:29, Mux.scala:27:73, Xbar.scala:431:50]
  reg  [9:0]  beatsLeft_2;	// @[Arbiter.scala:88:30]
  wire        idle_2 = beatsLeft_2 == 10'h0;	// @[Arbiter.scala:88:30, :89:28, Edges.scala:221:14]
  wire [1:0]  readys_valid_2 = {out_9_earlyValid, out_8_earlyValid};	// @[Cat.scala:33:92, Xbar.scala:182:40]
  reg  [1:0]  readys_mask_2;	// @[Arbiter.scala:24:23]
  wire [1:0]  _readys_filter_T_5 = readys_valid_2 & ~readys_mask_2;	// @[Arbiter.scala:24:23, :25:{28,30}, Cat.scala:33:92]
  wire [1:0]  readys_readys_2 = ~({readys_mask_2[1], _readys_filter_T_5[1] | readys_mask_2[0]} & {|_readys_filter_T_5, out_9_earlyValid | _readys_filter_T_5[0]});	// @[Arbiter.scala:24:23, :25:28, :26:58, :27:{18,29,39,48}, Xbar.scala:182:40, package.scala:254:43]
  wire        earlyWinner_2_0 = readys_readys_2[0] & out_8_earlyValid;	// @[Arbiter.scala:27:18, :96:86, :98:79, Xbar.scala:182:40]
  wire        earlyWinner_2_1 = readys_readys_2[1] & out_9_earlyValid;	// @[Arbiter.scala:27:18, :96:86, :98:79, Xbar.scala:182:40]
  wire        _sink_ACancel_earlyValid_T = out_8_earlyValid | out_9_earlyValid;	// @[Arbiter.scala:108:36, Xbar.scala:182:40]
  reg         state_2_0;	// @[Arbiter.scala:117:26]
  reg         state_2_1;	// @[Arbiter.scala:117:26]
  wire        muxStateEarly_2_0 = idle_2 ? earlyWinner_2_0 : state_2_0;	// @[Arbiter.scala:89:28, :98:79, :117:26, :118:30]
  wire        muxStateEarly_2_1 = idle_2 ? earlyWinner_2_1 : state_2_1;	// @[Arbiter.scala:89:28, :98:79, :117:26, :118:30]
  assign allowed_2_0 = idle_2 ? readys_readys_2[0] : state_2_0;	// @[Arbiter.scala:27:18, :89:28, :96:86, :117:26, :122:24]
  assign allowed_2_1 = idle_2 ? readys_readys_2[1] : state_2_1;	// @[Arbiter.scala:27:18, :89:28, :96:86, :117:26, :122:24]
  wire        out_10_valid = idle_2 ? _sink_ACancel_earlyValid_T : state_2_0 & out_8_earlyValid | state_2_1 & out_9_earlyValid;	// @[Arbiter.scala:89:28, :108:36, :117:26, :126:29, Mux.scala:27:73, Xbar.scala:182:40]
  reg  [9:0]  beatsLeft_3;	// @[Arbiter.scala:88:30]
  wire        idle_3 = beatsLeft_3 == 10'h0;	// @[Arbiter.scala:88:30, :89:28, Edges.scala:221:14]
  wire [1:0]  readys_valid_3 = {out_13_earlyValid, out_12_earlyValid};	// @[Cat.scala:33:92, Xbar.scala:182:40]
  reg  [1:0]  readys_mask_3;	// @[Arbiter.scala:24:23]
  wire [1:0]  _readys_filter_T_7 = readys_valid_3 & ~readys_mask_3;	// @[Arbiter.scala:24:23, :25:{28,30}, Cat.scala:33:92]
  wire [1:0]  readys_readys_3 = ~({readys_mask_3[1], _readys_filter_T_7[1] | readys_mask_3[0]} & {|_readys_filter_T_7, out_13_earlyValid | _readys_filter_T_7[0]});	// @[Arbiter.scala:24:23, :25:28, :26:58, :27:{18,29,39,48}, Xbar.scala:182:40, package.scala:254:43]
  wire        earlyWinner_3_0 = readys_readys_3[0] & out_12_earlyValid;	// @[Arbiter.scala:27:18, :96:86, :98:79, Xbar.scala:182:40]
  wire        earlyWinner_3_1 = readys_readys_3[1] & out_13_earlyValid;	// @[Arbiter.scala:27:18, :96:86, :98:79, Xbar.scala:182:40]
  wire        _sink_ACancel_earlyValid_T_5 = out_12_earlyValid | out_13_earlyValid;	// @[Arbiter.scala:108:36, Xbar.scala:182:40]
  reg         state_3_0;	// @[Arbiter.scala:117:26]
  reg         state_3_1;	// @[Arbiter.scala:117:26]
  wire        muxStateEarly_3_0 = idle_3 ? earlyWinner_3_0 : state_3_0;	// @[Arbiter.scala:89:28, :98:79, :117:26, :118:30]
  wire        muxStateEarly_3_1 = idle_3 ? earlyWinner_3_1 : state_3_1;	// @[Arbiter.scala:89:28, :98:79, :117:26, :118:30]
  assign allowed_3_0 = idle_3 ? readys_readys_3[0] : state_3_0;	// @[Arbiter.scala:27:18, :89:28, :96:86, :117:26, :122:24]
  assign allowed_3_1 = idle_3 ? readys_readys_3[1] : state_3_1;	// @[Arbiter.scala:27:18, :89:28, :96:86, :117:26, :122:24]
  wire        out_14_valid = idle_3 ? _sink_ACancel_earlyValid_T_5 : state_3_0 & out_12_earlyValid | state_3_1 & out_13_earlyValid;	// @[Arbiter.scala:89:28, :108:36, :117:26, :126:29, Mux.scala:27:73, Xbar.scala:182:40]
  wire [1:0]  _readys_mask_T = readys_readys & readys_valid;	// @[Arbiter.scala:27:18, :29:29, Cat.scala:33:92]
  wire [1:0]  _readys_mask_T_5 = readys_readys_1 & readys_valid_1;	// @[Arbiter.scala:27:18, :29:29, Cat.scala:33:92]
  wire [1:0]  _readys_mask_T_10 = readys_readys_2 & readys_valid_2;	// @[Arbiter.scala:27:18, :29:29, Cat.scala:33:92]
  wire [1:0]  _readys_mask_T_15 = readys_readys_3 & readys_valid_3;	// @[Arbiter.scala:27:18, :29:29, Cat.scala:33:92]
  wire [26:0] _beatsAI_decode_T_1 = 27'hFFF << auto_in_0_a_bits_size;	// @[package.scala:235:71]
  wire [26:0] _beatsAI_decode_T_5 = 27'hFFF << auto_in_1_a_bits_size;	// @[package.scala:235:71]
  wire [26:0] _beatsDO_decode_T_1 = 27'hFFF << auto_out_0_d_bits_size;	// @[package.scala:235:71]
  wire [20:0] _beatsDO_decode_T_5 = 21'h3F << auto_out_1_d_bits_size;	// @[package.scala:235:71]
  wire        latch = idle & auto_out_0_a_ready;	// @[Arbiter.scala:89:28, :90:24]
  wire        winnerQual_0 = readys_readys[0] & portsAOI_filtered_0_earlyValid;	// @[Arbiter.scala:27:18, :96:86, :99:79, Xbar.scala:431:50]
  wire        winnerQual_1 = readys_readys[1] & portsAOI_filtered_1_0_earlyValid;	// @[Arbiter.scala:27:18, :96:86, :99:79, Xbar.scala:431:50]
  wire        latch_1 = idle_1 & auto_out_1_a_ready;	// @[Arbiter.scala:89:28, :90:24]
  wire        winnerQual_1_0 = readys_readys_1[0] & portsAOI_filtered_1_earlyValid;	// @[Arbiter.scala:27:18, :96:86, :99:79, Xbar.scala:431:50]
  wire        winnerQual_1_1 = readys_readys_1[1] & portsAOI_filtered_1_1_earlyValid;	// @[Arbiter.scala:27:18, :96:86, :99:79, Xbar.scala:431:50]
  wire        latch_2 = idle_2 & auto_in_0_d_ready;	// @[Arbiter.scala:89:28, :90:24]
  wire        winnerQual_2_0 = readys_readys_2[0] & out_8_earlyValid;	// @[Arbiter.scala:27:18, :96:86, :99:79, Xbar.scala:182:40]
  wire        winnerQual_2_1 = readys_readys_2[1] & out_9_earlyValid;	// @[Arbiter.scala:27:18, :96:86, :99:79, Xbar.scala:182:40]
  wire        latch_3 = idle_3 & auto_in_1_d_ready;	// @[Arbiter.scala:89:28, :90:24]
  wire        winnerQual_3_0 = readys_readys_3[0] & out_12_earlyValid;	// @[Arbiter.scala:27:18, :96:86, :99:79, Xbar.scala:182:40]
  wire        winnerQual_3_1 = readys_readys_3[1] & out_13_earlyValid;	// @[Arbiter.scala:27:18, :96:86, :99:79, Xbar.scala:182:40]
  always @(posedge clock) begin
    if (reset) begin
      beatsLeft <= 10'h0;	// @[Arbiter.scala:88:30, Edges.scala:221:14]
      readys_mask <= 2'h3;	// @[Arbiter.scala:24:23, Parameters.scala:57:20]
      state_0 <= 1'h0;	// @[Arbiter.scala:117:26, Bundle_ACancel.scala:56:22]
      state_1 <= 1'h0;	// @[Arbiter.scala:117:26, Bundle_ACancel.scala:56:22]
      beatsLeft_1 <= 10'h0;	// @[Arbiter.scala:88:30, Edges.scala:221:14]
      readys_mask_1 <= 2'h3;	// @[Arbiter.scala:24:23, Parameters.scala:57:20]
      state_1_0 <= 1'h0;	// @[Arbiter.scala:117:26, Bundle_ACancel.scala:56:22]
      state_1_1 <= 1'h0;	// @[Arbiter.scala:117:26, Bundle_ACancel.scala:56:22]
      beatsLeft_2 <= 10'h0;	// @[Arbiter.scala:88:30, Edges.scala:221:14]
      readys_mask_2 <= 2'h3;	// @[Arbiter.scala:24:23, Parameters.scala:57:20]
      state_2_0 <= 1'h0;	// @[Arbiter.scala:117:26, Bundle_ACancel.scala:56:22]
      state_2_1 <= 1'h0;	// @[Arbiter.scala:117:26, Bundle_ACancel.scala:56:22]
      beatsLeft_3 <= 10'h0;	// @[Arbiter.scala:88:30, Edges.scala:221:14]
      readys_mask_3 <= 2'h3;	// @[Arbiter.scala:24:23, Parameters.scala:57:20]
      state_3_0 <= 1'h0;	// @[Arbiter.scala:117:26, Bundle_ACancel.scala:56:22]
      state_3_1 <= 1'h0;	// @[Arbiter.scala:117:26, Bundle_ACancel.scala:56:22]
    end
    else begin
      if (latch)	// @[Arbiter.scala:90:24]
        beatsLeft <= (winnerQual_0 & ~(auto_in_0_a_bits_opcode[2]) ? ~(_beatsAI_decode_T_1[11:2]) : 10'h0) | (winnerQual_1 & ~(auto_in_1_a_bits_opcode[2]) ? ~(_beatsAI_decode_T_5[11:2]) : 10'h0);	// @[Arbiter.scala:88:30, :99:79, :112:73, :113:44, Edges.scala:92:{28,37}, :221:14, package.scala:235:{46,71,76}]
      else	// @[Arbiter.scala:90:24]
        beatsLeft <= beatsLeft - {9'h0, auto_out_0_a_ready & x1_out_1_valid};	// @[Arbiter.scala:88:30, :114:52, :126:29, ReadyValidCancel.scala:49:33]
      if (latch & (|readys_valid))	// @[Arbiter.scala:28:{18,27}, :90:24, Cat.scala:33:92]
        readys_mask <= _readys_mask_T | {_readys_mask_T[0], 1'h0};	// @[Arbiter.scala:24:23, :29:29, Bundle_ACancel.scala:56:22, package.scala:245:{43,53}]
      if (idle) begin	// @[Arbiter.scala:89:28]
        state_0 <= winnerQual_0;	// @[Arbiter.scala:99:79, :117:26]
        state_1 <= winnerQual_1;	// @[Arbiter.scala:99:79, :117:26]
      end
      if (latch_1)	// @[Arbiter.scala:90:24]
        beatsLeft_1 <= (winnerQual_1_0 & ~(auto_in_0_a_bits_opcode[2]) ? ~(_beatsAI_decode_T_1[11:2]) : 10'h0) | (winnerQual_1_1 & ~(auto_in_1_a_bits_opcode[2]) ? ~(_beatsAI_decode_T_5[11:2]) : 10'h0);	// @[Arbiter.scala:88:30, :99:79, :112:73, :113:44, Edges.scala:92:{28,37}, :221:14, package.scala:235:{46,71,76}]
      else	// @[Arbiter.scala:90:24]
        beatsLeft_1 <= beatsLeft_1 - {9'h0, auto_out_1_a_ready & bundleOut_1_out_1_valid};	// @[Arbiter.scala:88:30, :114:52, :126:29, ReadyValidCancel.scala:49:33]
      if (latch_1 & (|readys_valid_1))	// @[Arbiter.scala:28:{18,27}, :90:24, Cat.scala:33:92]
        readys_mask_1 <= _readys_mask_T_5 | {_readys_mask_T_5[0], 1'h0};	// @[Arbiter.scala:24:23, :29:29, Bundle_ACancel.scala:56:22, package.scala:245:{43,53}]
      if (idle_1) begin	// @[Arbiter.scala:89:28]
        state_1_0 <= winnerQual_1_0;	// @[Arbiter.scala:99:79, :117:26]
        state_1_1 <= winnerQual_1_1;	// @[Arbiter.scala:99:79, :117:26]
      end
      if (latch_2)	// @[Arbiter.scala:90:24]
        beatsLeft_2 <= (winnerQual_2_0 & auto_out_0_d_bits_opcode[0] ? ~(_beatsDO_decode_T_1[11:2]) : 10'h0) | {6'h0, winnerQual_2_1 & auto_out_1_d_bits_opcode[0] ? ~(_beatsDO_decode_T_5[5:2]) : 4'h0};	// @[Arbiter.scala:88:30, :99:79, :112:73, :113:44, Bundles.scala:259:74, Edges.scala:106:36, :221:14, package.scala:235:{46,71,76}]
      else	// @[Arbiter.scala:90:24]
        beatsLeft_2 <= beatsLeft_2 - {9'h0, auto_in_0_d_ready & out_10_valid};	// @[Arbiter.scala:88:30, :114:52, :126:29, ReadyValidCancel.scala:49:33]
      if (latch_2 & (|readys_valid_2))	// @[Arbiter.scala:28:{18,27}, :90:24, Cat.scala:33:92]
        readys_mask_2 <= _readys_mask_T_10 | {_readys_mask_T_10[0], 1'h0};	// @[Arbiter.scala:24:23, :29:29, Bundle_ACancel.scala:56:22, package.scala:245:{43,53}]
      if (idle_2) begin	// @[Arbiter.scala:89:28]
        state_2_0 <= winnerQual_2_0;	// @[Arbiter.scala:99:79, :117:26]
        state_2_1 <= winnerQual_2_1;	// @[Arbiter.scala:99:79, :117:26]
      end
      if (latch_3)	// @[Arbiter.scala:90:24]
        beatsLeft_3 <= (winnerQual_3_0 & auto_out_0_d_bits_opcode[0] ? ~(_beatsDO_decode_T_1[11:2]) : 10'h0) | {6'h0, winnerQual_3_1 & auto_out_1_d_bits_opcode[0] ? ~(_beatsDO_decode_T_5[5:2]) : 4'h0};	// @[Arbiter.scala:88:30, :99:79, :112:73, :113:44, Bundles.scala:259:74, Edges.scala:106:36, :221:14, package.scala:235:{46,71,76}]
      else	// @[Arbiter.scala:90:24]
        beatsLeft_3 <= beatsLeft_3 - {9'h0, auto_in_1_d_ready & out_14_valid};	// @[Arbiter.scala:88:30, :114:52, :126:29, ReadyValidCancel.scala:49:33]
      if (latch_3 & (|readys_valid_3))	// @[Arbiter.scala:28:{18,27}, :90:24, Cat.scala:33:92]
        readys_mask_3 <= _readys_mask_T_15 | {_readys_mask_T_15[0], 1'h0};	// @[Arbiter.scala:24:23, :29:29, Bundle_ACancel.scala:56:22, package.scala:245:{43,53}]
      if (idle_3) begin	// @[Arbiter.scala:89:28]
        state_3_0 <= winnerQual_3_0;	// @[Arbiter.scala:99:79, :117:26]
        state_3_1 <= winnerQual_3_1;	// @[Arbiter.scala:99:79, :117:26]
      end
    end
  end // always @(posedge)
  `ifndef SYNTHESIS
    always @(posedge clock) begin	// @[Arbiter.scala:106:13]
      if (~reset & ~(~earlyWinner_0 | ~earlyWinner_1)) begin	// @[Arbiter.scala:98:79, :106:{13,61,64,67}]
        if (`ASSERT_VERBOSE_COND_)	// @[Arbiter.scala:106:13]
          $error("Assertion failed\n    at Arbiter.scala:106 assert((prefixOR zip earlyWinner) map { case (p,w) => !p || !w } reduce {_ && _})\n");	// @[Arbiter.scala:106:13]
        if (`STOP_COND_)	// @[Arbiter.scala:106:13]
          $fatal;	// @[Arbiter.scala:106:13]
      end
      if (~reset & ~(~_out_0_a_earlyValid_T | earlyWinner_0 | earlyWinner_1)) begin	// @[Arbiter.scala:98:79, :108:{14,15,36,41}]
        if (`ASSERT_VERBOSE_COND_)	// @[Arbiter.scala:108:14]
          $error("Assertion failed\n    at Arbiter.scala:108 assert (!earlyValids.reduce(_||_) || earlyWinner.reduce(_||_))\n");	// @[Arbiter.scala:108:14]
        if (`STOP_COND_)	// @[Arbiter.scala:108:14]
          $fatal;	// @[Arbiter.scala:108:14]
      end
      if (~reset & ~(~earlyWinner_1_0 | ~earlyWinner_1_1)) begin	// @[Arbiter.scala:98:79, :106:{13,61,64,67}]
        if (`ASSERT_VERBOSE_COND_)	// @[Arbiter.scala:106:13]
          $error("Assertion failed\n    at Arbiter.scala:106 assert((prefixOR zip earlyWinner) map { case (p,w) => !p || !w } reduce {_ && _})\n");	// @[Arbiter.scala:106:13]
        if (`STOP_COND_)	// @[Arbiter.scala:106:13]
          $fatal;	// @[Arbiter.scala:106:13]
      end
      if (~reset & ~(~_out_1_a_earlyValid_T | earlyWinner_1_0 | earlyWinner_1_1)) begin	// @[Arbiter.scala:98:79, :108:{14,15,36,41}]
        if (`ASSERT_VERBOSE_COND_)	// @[Arbiter.scala:108:14]
          $error("Assertion failed\n    at Arbiter.scala:108 assert (!earlyValids.reduce(_||_) || earlyWinner.reduce(_||_))\n");	// @[Arbiter.scala:108:14]
        if (`STOP_COND_)	// @[Arbiter.scala:108:14]
          $fatal;	// @[Arbiter.scala:108:14]
      end
      if (~reset & ~(~earlyWinner_2_0 | ~earlyWinner_2_1)) begin	// @[Arbiter.scala:98:79, :106:{13,61,64,67}]
        if (`ASSERT_VERBOSE_COND_)	// @[Arbiter.scala:106:13]
          $error("Assertion failed\n    at Arbiter.scala:106 assert((prefixOR zip earlyWinner) map { case (p,w) => !p || !w } reduce {_ && _})\n");	// @[Arbiter.scala:106:13]
        if (`STOP_COND_)	// @[Arbiter.scala:106:13]
          $fatal;	// @[Arbiter.scala:106:13]
      end
      if (~reset & ~(~_sink_ACancel_earlyValid_T | earlyWinner_2_0 | earlyWinner_2_1)) begin	// @[Arbiter.scala:98:79, :108:{14,15,36,41}]
        if (`ASSERT_VERBOSE_COND_)	// @[Arbiter.scala:108:14]
          $error("Assertion failed\n    at Arbiter.scala:108 assert (!earlyValids.reduce(_||_) || earlyWinner.reduce(_||_))\n");	// @[Arbiter.scala:108:14]
        if (`STOP_COND_)	// @[Arbiter.scala:108:14]
          $fatal;	// @[Arbiter.scala:108:14]
      end
      if (~reset & ~(~earlyWinner_3_0 | ~earlyWinner_3_1)) begin	// @[Arbiter.scala:98:79, :106:{13,61,64,67}]
        if (`ASSERT_VERBOSE_COND_)	// @[Arbiter.scala:106:13]
          $error("Assertion failed\n    at Arbiter.scala:106 assert((prefixOR zip earlyWinner) map { case (p,w) => !p || !w } reduce {_ && _})\n");	// @[Arbiter.scala:106:13]
        if (`STOP_COND_)	// @[Arbiter.scala:106:13]
          $fatal;	// @[Arbiter.scala:106:13]
      end
      if (~reset & ~(~_sink_ACancel_earlyValid_T_5 | earlyWinner_3_0 | earlyWinner_3_1)) begin	// @[Arbiter.scala:98:79, :108:{14,15,36,41}]
        if (`ASSERT_VERBOSE_COND_)	// @[Arbiter.scala:108:14]
          $error("Assertion failed\n    at Arbiter.scala:108 assert (!earlyValids.reduce(_||_) || earlyWinner.reduce(_||_))\n");	// @[Arbiter.scala:108:14]
        if (`STOP_COND_)	// @[Arbiter.scala:108:14]
          $fatal;	// @[Arbiter.scala:108:14]
      end
    end // always @(posedge)
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM_0;
    logic [31:0] _RANDOM_1;
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        _RANDOM_0 = `RANDOM;
        _RANDOM_1 = `RANDOM;
        beatsLeft = _RANDOM_0[9:0];	// @[Arbiter.scala:88:30]
        readys_mask = _RANDOM_0[11:10];	// @[Arbiter.scala:24:23, :88:30]
        state_0 = _RANDOM_0[12];	// @[Arbiter.scala:88:30, :117:26]
        state_1 = _RANDOM_0[13];	// @[Arbiter.scala:88:30, :117:26]
        beatsLeft_1 = _RANDOM_0[23:14];	// @[Arbiter.scala:88:30]
        readys_mask_1 = _RANDOM_0[25:24];	// @[Arbiter.scala:24:23, :88:30]
        state_1_0 = _RANDOM_0[26];	// @[Arbiter.scala:88:30, :117:26]
        state_1_1 = _RANDOM_0[27];	// @[Arbiter.scala:88:30, :117:26]
        beatsLeft_2 = {_RANDOM_0[31:28], _RANDOM_1[5:0]};	// @[Arbiter.scala:88:30]
        readys_mask_2 = _RANDOM_1[7:6];	// @[Arbiter.scala:24:23, :88:30]
        state_2_0 = _RANDOM_1[8];	// @[Arbiter.scala:88:30, :117:26]
        state_2_1 = _RANDOM_1[9];	// @[Arbiter.scala:88:30, :117:26]
        beatsLeft_3 = _RANDOM_1[19:10];	// @[Arbiter.scala:88:30]
        readys_mask_3 = _RANDOM_1[21:20];	// @[Arbiter.scala:24:23, :88:30]
        state_3_0 = _RANDOM_1[22];	// @[Arbiter.scala:88:30, :117:26]
        state_3_1 = _RANDOM_1[23];	// @[Arbiter.scala:88:30, :117:26]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // not def SYNTHESIS
  assign auto_in_1_a_ready = requestAIO_1_0 & auto_out_0_a_ready & allowed_1 | requestAIO_1_1 & auto_out_1_a_ready & allowed_1_1;	// @[Arbiter.scala:122:24, Mux.scala:27:73, Parameters.scala:137:65, Xbar.scala:366:92]
  assign auto_in_1_d_valid = out_14_valid;	// @[Arbiter.scala:126:29]
  assign auto_in_1_d_bits_opcode = (muxStateEarly_3_0 ? auto_out_0_d_bits_opcode : 3'h0) | (muxStateEarly_3_1 ? auto_out_1_d_bits_opcode : 3'h0);	// @[Arbiter.scala:118:30, Bundles.scala:259:74, Mux.scala:27:73]
  assign auto_in_1_d_bits_param = (muxStateEarly_3_0 ? auto_out_0_d_bits_param : 2'h0) | (muxStateEarly_3_1 ? auto_out_1_d_bits_param : 2'h0);	// @[Arbiter.scala:118:30, Bundles.scala:259:74, Mux.scala:27:73]
  assign auto_in_1_d_bits_size = (muxStateEarly_3_0 ? auto_out_0_d_bits_size : 4'h0) | (muxStateEarly_3_1 ? out_13_bits_size : 4'h0);	// @[Arbiter.scala:118:30, BundleMap.scala:247:19, Bundles.scala:259:74, Mux.scala:27:73]
  assign auto_in_1_d_bits_source = muxStateEarly_3_0 & auto_out_0_d_bits_source[0] | muxStateEarly_3_1 & auto_out_1_d_bits_source[0];	// @[Arbiter.scala:118:30, Mux.scala:27:73]
  assign auto_in_1_d_bits_sink = (muxStateEarly_3_0 ? out_12_bits_sink : 2'h0) | (muxStateEarly_3_1 ? auto_out_1_d_bits_sink : 2'h0);	// @[Arbiter.scala:118:30, Bundles.scala:259:74, Mux.scala:27:73, Xbar.scala:326:28]
  assign auto_in_1_d_bits_denied = muxStateEarly_3_0 & auto_out_0_d_bits_denied | muxStateEarly_3_1 & auto_out_1_d_bits_denied;	// @[Arbiter.scala:118:30, Mux.scala:27:73]
  assign auto_in_1_d_bits_data = (muxStateEarly_3_0 ? auto_out_0_d_bits_data : 32'h0) | (muxStateEarly_3_1 ? auto_out_1_d_bits_data : 32'h0);	// @[Arbiter.scala:118:30, Bundles.scala:259:74, Mux.scala:27:73]
  assign auto_in_1_d_bits_corrupt = muxStateEarly_3_0 & auto_out_0_d_bits_corrupt | muxStateEarly_3_1 & auto_out_1_d_bits_corrupt;	// @[Arbiter.scala:118:30, Mux.scala:27:73]
  assign auto_in_0_a_ready = requestAIO_0_0 & auto_out_0_a_ready & allowed_0 | requestAIO_0_1 & auto_out_1_a_ready & allowed_1_0;	// @[Arbiter.scala:122:24, Mux.scala:27:73, Parameters.scala:137:65, Xbar.scala:366:92]
  assign auto_in_0_d_valid = out_10_valid;	// @[Arbiter.scala:126:29]
  assign auto_in_0_d_bits_opcode = (muxStateEarly_2_0 ? auto_out_0_d_bits_opcode : 3'h0) | (muxStateEarly_2_1 ? auto_out_1_d_bits_opcode : 3'h0);	// @[Arbiter.scala:118:30, Bundles.scala:259:74, Mux.scala:27:73]
  assign auto_in_0_d_bits_param = (muxStateEarly_2_0 ? auto_out_0_d_bits_param : 2'h0) | (muxStateEarly_2_1 ? auto_out_1_d_bits_param : 2'h0);	// @[Arbiter.scala:118:30, Bundles.scala:259:74, Mux.scala:27:73]
  assign auto_in_0_d_bits_size = (muxStateEarly_2_0 ? auto_out_0_d_bits_size : 4'h0) | (muxStateEarly_2_1 ? out_13_bits_size : 4'h0);	// @[Arbiter.scala:118:30, BundleMap.scala:247:19, Bundles.scala:259:74, Mux.scala:27:73]
  assign auto_in_0_d_bits_source = (muxStateEarly_2_0 ? auto_out_0_d_bits_source[3:0] : 4'h0) | (muxStateEarly_2_1 ? auto_out_1_d_bits_source[3:0] : 4'h0);	// @[Arbiter.scala:118:30, Bundles.scala:259:74, Mux.scala:27:73]
  assign auto_in_0_d_bits_sink = (muxStateEarly_2_0 ? out_12_bits_sink : 2'h0) | (muxStateEarly_2_1 ? auto_out_1_d_bits_sink : 2'h0);	// @[Arbiter.scala:118:30, Bundles.scala:259:74, Mux.scala:27:73, Xbar.scala:326:28]
  assign auto_in_0_d_bits_denied = muxStateEarly_2_0 & auto_out_0_d_bits_denied | muxStateEarly_2_1 & auto_out_1_d_bits_denied;	// @[Arbiter.scala:118:30, Mux.scala:27:73]
  assign auto_in_0_d_bits_data = (muxStateEarly_2_0 ? auto_out_0_d_bits_data : 32'h0) | (muxStateEarly_2_1 ? auto_out_1_d_bits_data : 32'h0);	// @[Arbiter.scala:118:30, Bundles.scala:259:74, Mux.scala:27:73]
  assign auto_in_0_d_bits_corrupt = muxStateEarly_2_0 & auto_out_0_d_bits_corrupt | muxStateEarly_2_1 & auto_out_1_d_bits_corrupt;	// @[Arbiter.scala:118:30, Mux.scala:27:73]
  assign auto_out_1_a_valid = bundleOut_1_out_1_valid;	// @[Arbiter.scala:126:29]
  assign auto_out_1_a_bits_opcode = (muxStateEarly_1_0 ? auto_in_0_a_bits_opcode : 3'h0) | (muxStateEarly_1_1 ? auto_in_1_a_bits_opcode : 3'h0);	// @[Arbiter.scala:118:30, Bundles.scala:259:74, Mux.scala:27:73]
  assign auto_out_1_a_bits_size = (muxStateEarly_1_0 ? auto_in_0_a_bits_size[2:0] : 3'h0) | (muxStateEarly_1_1 ? auto_in_1_a_bits_size[2:0] : 3'h0);	// @[Arbiter.scala:118:30, Bundles.scala:259:74, Mux.scala:27:73]
  assign auto_out_1_a_bits_source = (muxStateEarly_1_0 ? portsAOI_filtered_1_bits_source : 5'h0) | (muxStateEarly_1_1 ? portsAOI_filtered_1_1_bits_source : 5'h0);	// @[Arbiter.scala:118:30, Mux.scala:27:73, Xbar.scala:240:{29,55}, :265:23]
  assign auto_out_1_a_bits_address = (muxStateEarly_1_0 ? auto_in_0_a_bits_address : 32'h0) | (muxStateEarly_1_1 ? auto_in_1_a_bits_address : 32'h0);	// @[Arbiter.scala:118:30, Bundles.scala:259:74, Mux.scala:27:73]
  assign auto_out_1_a_bits_user_amba_prot_bufferable = muxStateEarly_1_1 & auto_in_1_a_bits_user_amba_prot_bufferable;	// @[Arbiter.scala:118:30, Mux.scala:27:73]
  assign auto_out_1_a_bits_user_amba_prot_modifiable = muxStateEarly_1_1 & auto_in_1_a_bits_user_amba_prot_modifiable;	// @[Arbiter.scala:118:30, Mux.scala:27:73]
  assign auto_out_1_a_bits_user_amba_prot_readalloc = muxStateEarly_1_1 & auto_in_1_a_bits_user_amba_prot_readalloc;	// @[Arbiter.scala:118:30, Mux.scala:27:73]
  assign auto_out_1_a_bits_user_amba_prot_writealloc = muxStateEarly_1_1 & auto_in_1_a_bits_user_amba_prot_writealloc;	// @[Arbiter.scala:118:30, Mux.scala:27:73]
  assign auto_out_1_a_bits_user_amba_prot_privileged = muxStateEarly_1_0 | muxStateEarly_1_1 & auto_in_1_a_bits_user_amba_prot_privileged;	// @[Arbiter.scala:118:30, Mux.scala:27:73]
  assign auto_out_1_a_bits_user_amba_prot_secure = muxStateEarly_1_0 | muxStateEarly_1_1 & auto_in_1_a_bits_user_amba_prot_secure;	// @[Arbiter.scala:118:30, Mux.scala:27:73]
  assign auto_out_1_a_bits_user_amba_prot_fetch = muxStateEarly_1_1 & auto_in_1_a_bits_user_amba_prot_fetch;	// @[Arbiter.scala:118:30, Mux.scala:27:73]
  assign auto_out_1_a_bits_mask = (muxStateEarly_1_0 ? auto_in_0_a_bits_mask : 4'h0) | (muxStateEarly_1_1 ? auto_in_1_a_bits_mask : 4'h0);	// @[Arbiter.scala:118:30, Bundles.scala:259:74, Mux.scala:27:73]
  assign auto_out_1_a_bits_data = (muxStateEarly_1_0 ? auto_in_0_a_bits_data : 32'h0) | (muxStateEarly_1_1 ? auto_in_1_a_bits_data : 32'h0);	// @[Arbiter.scala:118:30, Bundles.scala:259:74, Mux.scala:27:73]
  assign auto_out_1_d_ready = ~(auto_out_1_d_bits_source[4]) & auto_in_0_d_ready & allowed_2_1 | requestDOI_1_1 & auto_in_1_d_ready & allowed_3_1;	// @[Arbiter.scala:122:24, Mux.scala:27:73, Parameters.scala:54:{10,32}]
  assign auto_out_0_a_valid = x1_out_1_valid;	// @[Arbiter.scala:126:29]
  assign auto_out_0_a_bits_opcode = (muxStateEarly_0 ? auto_in_0_a_bits_opcode : 3'h0) | (muxStateEarly_1 ? auto_in_1_a_bits_opcode : 3'h0);	// @[Arbiter.scala:118:30, Bundles.scala:259:74, Mux.scala:27:73]
  assign auto_out_0_a_bits_param = (muxStateEarly_0 ? auto_in_0_a_bits_param : 3'h0) | (muxStateEarly_1 ? auto_in_1_a_bits_param : 3'h0);	// @[Arbiter.scala:118:30, Bundles.scala:259:74, Mux.scala:27:73]
  assign auto_out_0_a_bits_size = (muxStateEarly_0 ? auto_in_0_a_bits_size : 4'h0) | (muxStateEarly_1 ? auto_in_1_a_bits_size : 4'h0);	// @[Arbiter.scala:118:30, Bundles.scala:259:74, Mux.scala:27:73]
  assign auto_out_0_a_bits_source = (muxStateEarly_0 ? portsAOI_filtered_1_bits_source : 5'h0) | (muxStateEarly_1 ? portsAOI_filtered_1_1_bits_source : 5'h0);	// @[Arbiter.scala:118:30, Mux.scala:27:73, Xbar.scala:240:{29,55}, :265:23]
  assign auto_out_0_a_bits_address = (muxStateEarly_0 ? auto_in_0_a_bits_address : 32'h0) | (muxStateEarly_1 ? auto_in_1_a_bits_address : 32'h0);	// @[Arbiter.scala:118:30, Bundles.scala:259:74, Mux.scala:27:73]
  assign auto_out_0_a_bits_mask = (muxStateEarly_0 ? auto_in_0_a_bits_mask : 4'h0) | (muxStateEarly_1 ? auto_in_1_a_bits_mask : 4'h0);	// @[Arbiter.scala:118:30, Bundles.scala:259:74, Mux.scala:27:73]
  assign auto_out_0_a_bits_data = (muxStateEarly_0 ? auto_in_0_a_bits_data : 32'h0) | (muxStateEarly_1 ? auto_in_1_a_bits_data : 32'h0);	// @[Arbiter.scala:118:30, Bundles.scala:259:74, Mux.scala:27:73]
  assign auto_out_0_a_bits_corrupt = muxStateEarly_0 & auto_in_0_a_bits_corrupt | muxStateEarly_1 & auto_in_1_a_bits_corrupt;	// @[Arbiter.scala:118:30, Mux.scala:27:73]
  assign auto_out_0_d_ready = ~(auto_out_0_d_bits_source[4]) & auto_in_0_d_ready & allowed_2_0 | requestDOI_0_1 & auto_in_1_d_ready & allowed_3_0;	// @[Arbiter.scala:122:24, Mux.scala:27:73, Parameters.scala:54:{10,32}]
endmodule

