// Generated by CIRCT unknown git version
// Standard header to adapt well known macros to our needs.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

module VC707woDDRHarness(
  input sys_clock_p,
        sys_clock_n,
  inout jtag_jtag_TCK,
        jtag_jtag_TMS,
        jtag_jtag_TDI,
        jtag_jtag_TDO,
        jtag_srst_n,
        uart_txd,
        uart_rxd,
        uart_rtsn,
        uart_ctsn,
        sdio_spi_clk,
        sdio_spi_cs,
        sdio_spi_dat_0,
        sdio_spi_dat_1,
        sdio_spi_dat_2,
        sdio_spi_dat_3,
  input reset
);

  wire        _WIRE;	// @[Harness.scala:157:38]
  wire        _harnessBinderReset_catcher_io_sync_reset;	// @[ResetCatchAndSync.scala:39:28]
  wire        _simdram_axi_aw_ready;	// @[HarnessBinders.scala:186:23]
  wire        _simdram_axi_w_ready;	// @[HarnessBinders.scala:186:23]
  wire        _simdram_axi_b_valid;	// @[HarnessBinders.scala:186:23]
  wire [3:0]  _simdram_axi_b_bits_id;	// @[HarnessBinders.scala:186:23]
  wire [1:0]  _simdram_axi_b_bits_resp;	// @[HarnessBinders.scala:186:23]
  wire        _simdram_axi_ar_ready;	// @[HarnessBinders.scala:186:23]
  wire        _simdram_axi_r_valid;	// @[HarnessBinders.scala:186:23]
  wire [3:0]  _simdram_axi_r_bits_id;	// @[HarnessBinders.scala:186:23]
  wire [31:0] _simdram_axi_r_bits_data;	// @[HarnessBinders.scala:186:23]
  wire [1:0]  _simdram_axi_r_bits_resp;	// @[HarnessBinders.scala:186:23]
  wire        _simdram_axi_r_bits_last;	// @[HarnessBinders.scala:186:23]
  wire        _plusarg_reader_out;	// @[PlusArg.scala:80:11]
  wire        _ram_io_ser_in_valid;	// @[TSIHarness.scala:24:24]
  wire [31:0] _ram_io_ser_in_bits;	// @[TSIHarness.scala:24:24]
  wire        _ram_io_ser_out_ready;	// @[TSIHarness.scala:24:24]
  wire        _chiptop0_serial_tl_bits_in_ready;	// @[HasHarnessInstantiators.scala:82:40]
  wire        _chiptop0_serial_tl_bits_out_valid;	// @[HasHarnessInstantiators.scala:82:40]
  wire [31:0] _chiptop0_serial_tl_bits_out_bits;	// @[HasHarnessInstantiators.scala:82:40]
  wire        _chiptop0_axi4_mem_0_clock;	// @[HasHarnessInstantiators.scala:82:40]
  wire        _chiptop0_axi4_mem_0_reset;	// @[HasHarnessInstantiators.scala:82:40]
  wire        _chiptop0_axi4_mem_0_bits_aw_valid;	// @[HasHarnessInstantiators.scala:82:40]
  wire [3:0]  _chiptop0_axi4_mem_0_bits_aw_bits_id;	// @[HasHarnessInstantiators.scala:82:40]
  wire [31:0] _chiptop0_axi4_mem_0_bits_aw_bits_addr;	// @[HasHarnessInstantiators.scala:82:40]
  wire [7:0]  _chiptop0_axi4_mem_0_bits_aw_bits_len;	// @[HasHarnessInstantiators.scala:82:40]
  wire [2:0]  _chiptop0_axi4_mem_0_bits_aw_bits_size;	// @[HasHarnessInstantiators.scala:82:40]
  wire [1:0]  _chiptop0_axi4_mem_0_bits_aw_bits_burst;	// @[HasHarnessInstantiators.scala:82:40]
  wire        _chiptop0_axi4_mem_0_bits_aw_bits_lock;	// @[HasHarnessInstantiators.scala:82:40]
  wire [3:0]  _chiptop0_axi4_mem_0_bits_aw_bits_cache;	// @[HasHarnessInstantiators.scala:82:40]
  wire [2:0]  _chiptop0_axi4_mem_0_bits_aw_bits_prot;	// @[HasHarnessInstantiators.scala:82:40]
  wire [3:0]  _chiptop0_axi4_mem_0_bits_aw_bits_qos;	// @[HasHarnessInstantiators.scala:82:40]
  wire        _chiptop0_axi4_mem_0_bits_w_valid;	// @[HasHarnessInstantiators.scala:82:40]
  wire [31:0] _chiptop0_axi4_mem_0_bits_w_bits_data;	// @[HasHarnessInstantiators.scala:82:40]
  wire [3:0]  _chiptop0_axi4_mem_0_bits_w_bits_strb;	// @[HasHarnessInstantiators.scala:82:40]
  wire        _chiptop0_axi4_mem_0_bits_w_bits_last;	// @[HasHarnessInstantiators.scala:82:40]
  wire        _chiptop0_axi4_mem_0_bits_b_ready;	// @[HasHarnessInstantiators.scala:82:40]
  wire        _chiptop0_axi4_mem_0_bits_ar_valid;	// @[HasHarnessInstantiators.scala:82:40]
  wire [3:0]  _chiptop0_axi4_mem_0_bits_ar_bits_id;	// @[HasHarnessInstantiators.scala:82:40]
  wire [31:0] _chiptop0_axi4_mem_0_bits_ar_bits_addr;	// @[HasHarnessInstantiators.scala:82:40]
  wire [7:0]  _chiptop0_axi4_mem_0_bits_ar_bits_len;	// @[HasHarnessInstantiators.scala:82:40]
  wire [2:0]  _chiptop0_axi4_mem_0_bits_ar_bits_size;	// @[HasHarnessInstantiators.scala:82:40]
  wire [1:0]  _chiptop0_axi4_mem_0_bits_ar_bits_burst;	// @[HasHarnessInstantiators.scala:82:40]
  wire        _chiptop0_axi4_mem_0_bits_ar_bits_lock;	// @[HasHarnessInstantiators.scala:82:40]
  wire [3:0]  _chiptop0_axi4_mem_0_bits_ar_bits_cache;	// @[HasHarnessInstantiators.scala:82:40]
  wire [2:0]  _chiptop0_axi4_mem_0_bits_ar_bits_prot;	// @[HasHarnessInstantiators.scala:82:40]
  wire [3:0]  _chiptop0_axi4_mem_0_bits_ar_bits_qos;	// @[HasHarnessInstantiators.scala:82:40]
  wire        _chiptop0_axi4_mem_0_bits_r_ready;	// @[HasHarnessInstantiators.scala:82:40]
  wire        _chiptop0_jtag_TDO;	// @[HasHarnessInstantiators.scala:82:40]
  wire        _chiptop0_spi_0_sck;	// @[HasHarnessInstantiators.scala:82:40]
  wire        _chiptop0_spi_0_dq_0_o;	// @[HasHarnessInstantiators.scala:82:40]
  wire        _chiptop0_spi_0_dq_0_ie;	// @[HasHarnessInstantiators.scala:82:40]
  wire        _chiptop0_spi_0_dq_0_oe;	// @[HasHarnessInstantiators.scala:82:40]
  wire        _chiptop0_spi_0_dq_1_o;	// @[HasHarnessInstantiators.scala:82:40]
  wire        _chiptop0_spi_0_dq_1_ie;	// @[HasHarnessInstantiators.scala:82:40]
  wire        _chiptop0_spi_0_dq_1_oe;	// @[HasHarnessInstantiators.scala:82:40]
  wire        _chiptop0_spi_0_dq_2_o;	// @[HasHarnessInstantiators.scala:82:40]
  wire        _chiptop0_spi_0_dq_2_ie;	// @[HasHarnessInstantiators.scala:82:40]
  wire        _chiptop0_spi_0_dq_2_oe;	// @[HasHarnessInstantiators.scala:82:40]
  wire        _chiptop0_spi_0_dq_3_o;	// @[HasHarnessInstantiators.scala:82:40]
  wire        _chiptop0_spi_0_dq_3_ie;	// @[HasHarnessInstantiators.scala:82:40]
  wire        _chiptop0_spi_0_dq_3_oe;	// @[HasHarnessInstantiators.scala:82:40]
  wire        _chiptop0_spi_0_cs_0;	// @[HasHarnessInstantiators.scala:82:40]
  wire        _chiptop0_uart_0_txd;	// @[HasHarnessInstantiators.scala:82:40]
  wire        _fpga_power_on_power_on_reset;	// @[Xilinx.scala:104:21]
  wire        _resetIBUF_O;	// @[Harness.scala:149:25]
  wire        _a2b_5_b;	// @[Util.scala:30:21]
  wire        _bundleIn_0_rxd_a2b_b;	// @[Util.scala:30:21]
  wire        _bundleIn_0_srst_n_a2b_b;	// @[Util.scala:30:21]
  wire        _bundleIn_0_TDI_a2b_b;	// @[Util.scala:30:21]
  wire        _bundleIn_0_TMS_a2b_b;	// @[Util.scala:30:21]
  wire        _bundleIn_0_TCK_a2b_b;	// @[Util.scala:30:21]
  wire        _sys_clock_ibufds_O;	// @[ClockOverlay.scala:14:24]
  wire        _harnessSysPLL_clk_out1;	// @[XilinxShell.scala:76:55]
  wire        _harnessSysPLL_locked;	// @[XilinxShell.scala:76:55]
  wire        _dutGroup_auto_out_clock;	// @[ClockGroup.scala:31:15]
  wire        _dutGroup_auto_out_reset;	// @[ClockGroup.scala:31:15]
  wire        _dutWrangler_auto_out_clock;	// @[Harness.scala:120:31]
  wire        _dutWrangler_auto_out_reset;	// @[Harness.scala:120:31]
  reg         bundleIn_0_dq_1_i_REG;	// @[SDIOOverlay.scala:19:39]
  reg         bundleIn_0_dq_1_i_REG_1;	// @[SDIOOverlay.scala:19:31]
  assign _WIRE = _resetIBUF_O | _fpga_power_on_power_on_reset;	// @[Harness.scala:149:25, :157:38, Xilinx.scala:104:21]
  always @(posedge _dutWrangler_auto_out_clock) begin	// @[Harness.scala:120:31]
    bundleIn_0_dq_1_i_REG <= _a2b_5_b;	// @[SDIOOverlay.scala:19:39, Util.scala:30:21]
    bundleIn_0_dq_1_i_REG_1 <= bundleIn_0_dq_1_i_REG;	// @[SDIOOverlay.scala:19:{31,39}]
  end // always @(posedge)
  `ifndef SYNTHESIS
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM_0;
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        _RANDOM_0 = `RANDOM;
        bundleIn_0_dq_1_i_REG = _RANDOM_0[2];	// @[SDIOOverlay.scala:19:39]
        bundleIn_0_dq_1_i_REG_1 = _RANDOM_0[3];	// @[SDIOOverlay.scala:19:{31,39}]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // not def SYNTHESIS
  ResetWrangler dutWrangler (	// @[Harness.scala:120:31]
    .auto_in_clock  (_dutGroup_auto_out_clock),	// @[ClockGroup.scala:31:15]
    .auto_in_reset  (_dutGroup_auto_out_reset),	// @[ClockGroup.scala:31:15]
    .auto_out_clock (_dutWrangler_auto_out_clock),
    .auto_out_reset (_dutWrangler_auto_out_reset)
  );
  ClockGroup dutGroup (	// @[ClockGroup.scala:31:15]
    .auto_in_member_0_clock (_harnessSysPLL_clk_out1),	// @[XilinxShell.scala:76:55]
    .auto_in_member_0_reset (~_harnessSysPLL_locked | _WIRE),	// @[Harness.scala:157:38, PLLFactory.scala:78:{20,35}, XilinxShell.scala:76:55]
    .auto_out_clock         (_dutGroup_auto_out_clock),
    .auto_out_reset         (_dutGroup_auto_out_reset)
  );
  harnessSysPLL harnessSysPLL (	// @[XilinxShell.scala:76:55]
    .clk_in1  (_sys_clock_ibufds_O),	// @[ClockOverlay.scala:14:24]
    .reset    (_WIRE),	// @[Harness.scala:157:38]
    .clk_out1 (_harnessSysPLL_clk_out1),
    .locked   (_harnessSysPLL_locked)
  );
  IBUFDS #(
    .DIFF_TERM("FALSE"),
    .IOSTANDARD("DEFAULT"),
    .DQS_BIAS("FALSE"),
    .CAPACITANCE("DONT_CARE"),
    .IFD_DELAY_VALUE("AUTO"),
    .IBUF_LOW_PWR("TRUE"),
    .IBUF_DELAY_VALUE(0)
  ) sys_clock_ibufds (	// @[ClockOverlay.scala:14:24]
    .I  (sys_clock_p),
    .IB (sys_clock_n),
    .O  (_sys_clock_ibufds_O)
  );
  AnalogToUInt_1 bundleIn_0_TCK_a2b (	// @[Util.scala:30:21]
    .a (jtag_jtag_TCK),
    .b (_bundleIn_0_TCK_a2b_b)
  );
  AnalogToUInt_1 bundleIn_0_TMS_a2b (	// @[Util.scala:30:21]
    .a (jtag_jtag_TMS),
    .b (_bundleIn_0_TMS_a2b_b)
  );
  AnalogToUInt_1 bundleIn_0_TDI_a2b (	// @[Util.scala:30:21]
    .a (jtag_jtag_TDI),
    .b (_bundleIn_0_TDI_a2b_b)
  );
  UIntToAnalog_1 a2b (	// @[Util.scala:58:21]
    .a    (jtag_jtag_TDO),
    .b    (_chiptop0_jtag_TDO),	// @[HasHarnessInstantiators.scala:82:40]
    .b_en (1'h1)	// @[Util.scala:61:17]
  );
  AnalogToUInt_1 bundleIn_0_srst_n_a2b (	// @[Util.scala:30:21]
    .a (jtag_srst_n),
    .b (_bundleIn_0_srst_n_a2b_b)
  );
  UIntToAnalog_1 a2b_1 (	// @[Util.scala:58:21]
    .a    (uart_txd),
    .b    (_chiptop0_uart_0_txd),	// @[HasHarnessInstantiators.scala:82:40]
    .b_en (1'h1)	// @[Util.scala:61:17]
  );
  AnalogToUInt_1 bundleIn_0_rxd_a2b (	// @[Util.scala:30:21]
    .a (uart_rxd),
    .b (_bundleIn_0_rxd_a2b_b)
  );
  UIntToAnalog_1 a2b_2 (	// @[Util.scala:58:21]
    .a    (sdio_spi_clk),
    .b    (_chiptop0_spi_0_sck),	// @[HasHarnessInstantiators.scala:82:40]
    .b_en (1'h1)	// @[Util.scala:61:17]
  );
  UIntToAnalog_1 a2b_3 (	// @[Util.scala:58:21]
    .a    (sdio_spi_dat_3),
    .b    (_chiptop0_spi_0_cs_0),	// @[HasHarnessInstantiators.scala:82:40]
    .b_en (1'h1)	// @[Util.scala:61:17]
  );
  UIntToAnalog_1 a2b_4 (	// @[Util.scala:58:21]
    .a    (sdio_spi_cs),
    .b    (_chiptop0_spi_0_dq_0_o),	// @[HasHarnessInstantiators.scala:82:40]
    .b_en (1'h1)	// @[Util.scala:61:17]
  );
  AnalogToUInt_1 a2b_5 (	// @[Util.scala:30:21]
    .a (sdio_spi_dat_0),
    .b (_a2b_5_b)
  );
  IBUF resetIBUF (	// @[Harness.scala:149:25]
    .I (reset),
    .O (_resetIBUF_O)
  );
  PowerOnResetFPGAOnly fpga_power_on (	// @[Xilinx.scala:104:21]
    .clock          (_sys_clock_ibufds_O),	// @[ClockOverlay.scala:14:24]
    .power_on_reset (_fpga_power_on_power_on_reset)
  );
  ChipTop chiptop0 (	// @[HasHarnessInstantiators.scala:82:40]
    .serial_tl_clock               (_dutWrangler_auto_out_clock),	// @[Harness.scala:120:31]
    .serial_tl_bits_in_valid       (_ram_io_ser_in_valid),	// @[TSIHarness.scala:24:24]
    .serial_tl_bits_in_bits        (_ram_io_ser_in_bits),	// @[TSIHarness.scala:24:24]
    .serial_tl_bits_out_ready      (_ram_io_ser_out_ready),	// @[TSIHarness.scala:24:24]
    .reset_io                      (_harnessBinderReset_catcher_io_sync_reset),	// @[ResetCatchAndSync.scala:39:28]
    .clock_uncore_clock            (_dutWrangler_auto_out_clock),	// @[Harness.scala:120:31]
    .axi4_mem_0_bits_aw_ready      (_simdram_axi_aw_ready),	// @[HarnessBinders.scala:186:23]
    .axi4_mem_0_bits_w_ready       (_simdram_axi_w_ready),	// @[HarnessBinders.scala:186:23]
    .axi4_mem_0_bits_b_valid       (_simdram_axi_b_valid),	// @[HarnessBinders.scala:186:23]
    .axi4_mem_0_bits_b_bits_id     (_simdram_axi_b_bits_id),	// @[HarnessBinders.scala:186:23]
    .axi4_mem_0_bits_b_bits_resp   (_simdram_axi_b_bits_resp),	// @[HarnessBinders.scala:186:23]
    .axi4_mem_0_bits_ar_ready      (_simdram_axi_ar_ready),	// @[HarnessBinders.scala:186:23]
    .axi4_mem_0_bits_r_valid       (_simdram_axi_r_valid),	// @[HarnessBinders.scala:186:23]
    .axi4_mem_0_bits_r_bits_id     (_simdram_axi_r_bits_id),	// @[HarnessBinders.scala:186:23]
    .axi4_mem_0_bits_r_bits_data   (_simdram_axi_r_bits_data),	// @[HarnessBinders.scala:186:23]
    .axi4_mem_0_bits_r_bits_resp   (_simdram_axi_r_bits_resp),	// @[HarnessBinders.scala:186:23]
    .axi4_mem_0_bits_r_bits_last   (_simdram_axi_r_bits_last),	// @[HarnessBinders.scala:186:23]
    .jtag_TCK                      (_bundleIn_0_TCK_a2b_b),	// @[Util.scala:30:21]
    .jtag_TMS                      (_bundleIn_0_TMS_a2b_b),	// @[Util.scala:30:21]
    .jtag_TDI                      (_bundleIn_0_TDI_a2b_b),	// @[Util.scala:30:21]
    .spi_0_dq_0_i                  (1'h0),	// @[LazyModule.scala:411:29]
    .spi_0_dq_1_i                  (bundleIn_0_dq_1_i_REG_1),	// @[SDIOOverlay.scala:19:31]
    .spi_0_dq_2_i                  (1'h0),	// @[LazyModule.scala:411:29]
    .spi_0_dq_3_i                  (1'h0),	// @[LazyModule.scala:411:29]
    .uart_0_rxd                    (_bundleIn_0_rxd_a2b_b),	// @[Util.scala:30:21]
    .serial_tl_bits_in_ready       (_chiptop0_serial_tl_bits_in_ready),
    .serial_tl_bits_out_valid      (_chiptop0_serial_tl_bits_out_valid),
    .serial_tl_bits_out_bits       (_chiptop0_serial_tl_bits_out_bits),
    .axi4_mem_0_clock              (_chiptop0_axi4_mem_0_clock),
    .axi4_mem_0_reset              (_chiptop0_axi4_mem_0_reset),
    .axi4_mem_0_bits_aw_valid      (_chiptop0_axi4_mem_0_bits_aw_valid),
    .axi4_mem_0_bits_aw_bits_id    (_chiptop0_axi4_mem_0_bits_aw_bits_id),
    .axi4_mem_0_bits_aw_bits_addr  (_chiptop0_axi4_mem_0_bits_aw_bits_addr),
    .axi4_mem_0_bits_aw_bits_len   (_chiptop0_axi4_mem_0_bits_aw_bits_len),
    .axi4_mem_0_bits_aw_bits_size  (_chiptop0_axi4_mem_0_bits_aw_bits_size),
    .axi4_mem_0_bits_aw_bits_burst (_chiptop0_axi4_mem_0_bits_aw_bits_burst),
    .axi4_mem_0_bits_aw_bits_lock  (_chiptop0_axi4_mem_0_bits_aw_bits_lock),
    .axi4_mem_0_bits_aw_bits_cache (_chiptop0_axi4_mem_0_bits_aw_bits_cache),
    .axi4_mem_0_bits_aw_bits_prot  (_chiptop0_axi4_mem_0_bits_aw_bits_prot),
    .axi4_mem_0_bits_aw_bits_qos   (_chiptop0_axi4_mem_0_bits_aw_bits_qos),
    .axi4_mem_0_bits_w_valid       (_chiptop0_axi4_mem_0_bits_w_valid),
    .axi4_mem_0_bits_w_bits_data   (_chiptop0_axi4_mem_0_bits_w_bits_data),
    .axi4_mem_0_bits_w_bits_strb   (_chiptop0_axi4_mem_0_bits_w_bits_strb),
    .axi4_mem_0_bits_w_bits_last   (_chiptop0_axi4_mem_0_bits_w_bits_last),
    .axi4_mem_0_bits_b_ready       (_chiptop0_axi4_mem_0_bits_b_ready),
    .axi4_mem_0_bits_ar_valid      (_chiptop0_axi4_mem_0_bits_ar_valid),
    .axi4_mem_0_bits_ar_bits_id    (_chiptop0_axi4_mem_0_bits_ar_bits_id),
    .axi4_mem_0_bits_ar_bits_addr  (_chiptop0_axi4_mem_0_bits_ar_bits_addr),
    .axi4_mem_0_bits_ar_bits_len   (_chiptop0_axi4_mem_0_bits_ar_bits_len),
    .axi4_mem_0_bits_ar_bits_size  (_chiptop0_axi4_mem_0_bits_ar_bits_size),
    .axi4_mem_0_bits_ar_bits_burst (_chiptop0_axi4_mem_0_bits_ar_bits_burst),
    .axi4_mem_0_bits_ar_bits_lock  (_chiptop0_axi4_mem_0_bits_ar_bits_lock),
    .axi4_mem_0_bits_ar_bits_cache (_chiptop0_axi4_mem_0_bits_ar_bits_cache),
    .axi4_mem_0_bits_ar_bits_prot  (_chiptop0_axi4_mem_0_bits_ar_bits_prot),
    .axi4_mem_0_bits_ar_bits_qos   (_chiptop0_axi4_mem_0_bits_ar_bits_qos),
    .axi4_mem_0_bits_r_ready       (_chiptop0_axi4_mem_0_bits_r_ready),
    .jtag_TDO                      (_chiptop0_jtag_TDO),
    .spi_0_sck                     (_chiptop0_spi_0_sck),
    .spi_0_dq_0_o                  (_chiptop0_spi_0_dq_0_o),
    .spi_0_dq_0_ie                 (_chiptop0_spi_0_dq_0_ie),
    .spi_0_dq_0_oe                 (_chiptop0_spi_0_dq_0_oe),
    .spi_0_dq_1_o                  (_chiptop0_spi_0_dq_1_o),
    .spi_0_dq_1_ie                 (_chiptop0_spi_0_dq_1_ie),
    .spi_0_dq_1_oe                 (_chiptop0_spi_0_dq_1_oe),
    .spi_0_dq_2_o                  (_chiptop0_spi_0_dq_2_o),
    .spi_0_dq_2_ie                 (_chiptop0_spi_0_dq_2_ie),
    .spi_0_dq_2_oe                 (_chiptop0_spi_0_dq_2_oe),
    .spi_0_dq_3_o                  (_chiptop0_spi_0_dq_3_o),
    .spi_0_dq_3_ie                 (_chiptop0_spi_0_dq_3_ie),
    .spi_0_dq_3_oe                 (_chiptop0_spi_0_dq_3_oe),
    .spi_0_cs_0                    (_chiptop0_spi_0_cs_0),
    .uart_0_txd                    (_chiptop0_uart_0_txd)
  );
  SerialRAM ram (	// @[TSIHarness.scala:24:24]
    .clock            (_dutWrangler_auto_out_clock),	// @[Harness.scala:120:31]
    .reset            (_harnessBinderReset_catcher_io_sync_reset),	// @[ResetCatchAndSync.scala:39:28]
    .io_ser_in_ready  (_chiptop0_serial_tl_bits_in_ready),	// @[HasHarnessInstantiators.scala:82:40]
    .io_ser_out_valid (_chiptop0_serial_tl_bits_out_valid),	// @[HasHarnessInstantiators.scala:82:40]
    .io_ser_out_bits  (_chiptop0_serial_tl_bits_out_bits),	// @[HasHarnessInstantiators.scala:82:40]
    .io_ser_in_valid  (_ram_io_ser_in_valid),
    .io_ser_in_bits   (_ram_io_ser_in_bits),
    .io_ser_out_ready (_ram_io_ser_out_ready)
  );
  plusarg_reader_VC707woDDRHarness_UNIQUIFIED #(
    .FORMAT("custom_boot_pin=%d"),
    .DEFAULT(0),
    .WIDTH(1)
  ) plusarg_reader_VC707woDDRHarness_UNIQUIFIED (	// @[PlusArg.scala:80:11]
    .out (_plusarg_reader_out)
  );
  SimDRAM #(
    .MEM_BASE(40'd2147483648),
    .LINE_SIZE(64),
    .CLOCK_HZ(50000000),
    .ID_BITS(4),
    .ADDR_BITS(32),
    .MEM_SIZE(268435456),
    .DATA_BITS(32)
  ) simdram (	// @[HarnessBinders.scala:186:23]
    .clock             (_chiptop0_axi4_mem_0_clock),	// @[HasHarnessInstantiators.scala:82:40]
    .reset             (_chiptop0_axi4_mem_0_reset),	// @[HasHarnessInstantiators.scala:82:40]
    .axi_aw_valid      (_chiptop0_axi4_mem_0_bits_aw_valid),	// @[HasHarnessInstantiators.scala:82:40]
    .axi_aw_bits_id    (_chiptop0_axi4_mem_0_bits_aw_bits_id),	// @[HasHarnessInstantiators.scala:82:40]
    .axi_aw_bits_addr  (_chiptop0_axi4_mem_0_bits_aw_bits_addr),	// @[HasHarnessInstantiators.scala:82:40]
    .axi_aw_bits_len   (_chiptop0_axi4_mem_0_bits_aw_bits_len),	// @[HasHarnessInstantiators.scala:82:40]
    .axi_aw_bits_size  (_chiptop0_axi4_mem_0_bits_aw_bits_size),	// @[HasHarnessInstantiators.scala:82:40]
    .axi_aw_bits_burst (_chiptop0_axi4_mem_0_bits_aw_bits_burst),	// @[HasHarnessInstantiators.scala:82:40]
    .axi_aw_bits_lock  (_chiptop0_axi4_mem_0_bits_aw_bits_lock),	// @[HasHarnessInstantiators.scala:82:40]
    .axi_aw_bits_cache (_chiptop0_axi4_mem_0_bits_aw_bits_cache),	// @[HasHarnessInstantiators.scala:82:40]
    .axi_aw_bits_prot  (_chiptop0_axi4_mem_0_bits_aw_bits_prot),	// @[HasHarnessInstantiators.scala:82:40]
    .axi_aw_bits_qos   (_chiptop0_axi4_mem_0_bits_aw_bits_qos),	// @[HasHarnessInstantiators.scala:82:40]
    .axi_w_valid       (_chiptop0_axi4_mem_0_bits_w_valid),	// @[HasHarnessInstantiators.scala:82:40]
    .axi_w_bits_data   (_chiptop0_axi4_mem_0_bits_w_bits_data),	// @[HasHarnessInstantiators.scala:82:40]
    .axi_w_bits_strb   (_chiptop0_axi4_mem_0_bits_w_bits_strb),	// @[HasHarnessInstantiators.scala:82:40]
    .axi_w_bits_last   (_chiptop0_axi4_mem_0_bits_w_bits_last),	// @[HasHarnessInstantiators.scala:82:40]
    .axi_b_ready       (_chiptop0_axi4_mem_0_bits_b_ready),	// @[HasHarnessInstantiators.scala:82:40]
    .axi_ar_valid      (_chiptop0_axi4_mem_0_bits_ar_valid),	// @[HasHarnessInstantiators.scala:82:40]
    .axi_ar_bits_id    (_chiptop0_axi4_mem_0_bits_ar_bits_id),	// @[HasHarnessInstantiators.scala:82:40]
    .axi_ar_bits_addr  (_chiptop0_axi4_mem_0_bits_ar_bits_addr),	// @[HasHarnessInstantiators.scala:82:40]
    .axi_ar_bits_len   (_chiptop0_axi4_mem_0_bits_ar_bits_len),	// @[HasHarnessInstantiators.scala:82:40]
    .axi_ar_bits_size  (_chiptop0_axi4_mem_0_bits_ar_bits_size),	// @[HasHarnessInstantiators.scala:82:40]
    .axi_ar_bits_burst (_chiptop0_axi4_mem_0_bits_ar_bits_burst),	// @[HasHarnessInstantiators.scala:82:40]
    .axi_ar_bits_lock  (_chiptop0_axi4_mem_0_bits_ar_bits_lock),	// @[HasHarnessInstantiators.scala:82:40]
    .axi_ar_bits_cache (_chiptop0_axi4_mem_0_bits_ar_bits_cache),	// @[HasHarnessInstantiators.scala:82:40]
    .axi_ar_bits_prot  (_chiptop0_axi4_mem_0_bits_ar_bits_prot),	// @[HasHarnessInstantiators.scala:82:40]
    .axi_ar_bits_qos   (_chiptop0_axi4_mem_0_bits_ar_bits_qos),	// @[HasHarnessInstantiators.scala:82:40]
    .axi_r_ready       (_chiptop0_axi4_mem_0_bits_r_ready),	// @[HasHarnessInstantiators.scala:82:40]
    .axi_aw_ready      (_simdram_axi_aw_ready),
    .axi_w_ready       (_simdram_axi_w_ready),
    .axi_b_valid       (_simdram_axi_b_valid),
    .axi_b_bits_id     (_simdram_axi_b_bits_id),
    .axi_b_bits_resp   (_simdram_axi_b_bits_resp),
    .axi_ar_ready      (_simdram_axi_ar_ready),
    .axi_r_valid       (_simdram_axi_r_valid),
    .axi_r_bits_id     (_simdram_axi_r_bits_id),
    .axi_r_bits_data   (_simdram_axi_r_bits_data),
    .axi_r_bits_resp   (_simdram_axi_r_bits_resp),
    .axi_r_bits_last   (_simdram_axi_r_bits_last)
  );
  ResetCatchAndSync_d3_VC707woDDRHarness_UNIQUIFIED harnessBinderReset_catcher (	// @[ResetCatchAndSync.scala:39:28]
    .clock         (_dutWrangler_auto_out_clock),	// @[Harness.scala:120:31]
    .reset         (_dutWrangler_auto_out_reset),	// @[Harness.scala:120:31]
    .io_sync_reset (_harnessBinderReset_catcher_io_sync_reset)
  );
endmodule

