// Generated by CIRCT unknown git version
// Standard header to adapt well known macros to our needs.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

module ChipTop(
  input         tl_slave_0_a_ready,
                tl_slave_0_d_valid,
  input  [2:0]  tl_slave_0_d_bits_opcode,
  input  [1:0]  tl_slave_0_d_bits_param,
  input  [2:0]  tl_slave_0_d_bits_size,
  input  [3:0]  tl_slave_0_d_bits_source,
  input         tl_slave_0_d_bits_sink,
                tl_slave_0_d_bits_denied,
  input  [63:0] tl_slave_0_d_bits_data,
  input         tl_slave_0_d_bits_corrupt,
                custom_boot,
                reset_io,
                clock_uncore_clock,
                jtag_TCK,
                jtag_TMS,
                jtag_TDI,
                uart_0_rxd,
  output        tl_slave_0_a_valid,
  output [2:0]  tl_slave_0_a_bits_opcode,
                tl_slave_0_a_bits_param,
                tl_slave_0_a_bits_size,
  output [3:0]  tl_slave_0_a_bits_source,
  output [31:0] tl_slave_0_a_bits_address,
  output [7:0]  tl_slave_0_a_bits_mask,
  output [63:0] tl_slave_0_a_bits_data,
  output        tl_slave_0_a_bits_corrupt,
                tl_slave_0_d_ready,
                jtag_TDO,
                uart_0_txd
);

  wire _iocell_uart_0_rxd_i;	// @[IOCell.scala:111:23]
  wire _iocell_jtag_TCK_i;	// @[IOCell.scala:111:23]
  wire _iocell_jtag_TMS_i;	// @[IOCell.scala:111:23]
  wire _iocell_jtag_TDI_i;	// @[IOCell.scala:111:23]
  wire _dmactiveAck_dmactiveAck_io_q;	// @[ShiftReg.scala:45:23]
  wire _debug_reset_syncd_debug_reset_sync_io_q;	// @[ShiftReg.scala:45:23]
  wire _system_debug_systemjtag_reset_catcher_io_sync_reset;	// @[ResetCatchAndSync.scala:39:28]
  wire _iocell_custom_boot_i;	// @[IOCell.scala:111:23]
  wire _system_auto_implicitClockGrouper_out_clock;	// @[ChipTop.scala:28:35]
  wire _system_auto_implicitClockGrouper_out_reset;	// @[ChipTop.scala:28:35]
  wire _system_auto_subsystem_cbus_fixedClockNode_out_clock;	// @[ChipTop.scala:28:35]
  wire _system_auto_subsystem_cbus_fixedClockNode_out_reset;	// @[ChipTop.scala:28:35]
  wire _system_debug_systemjtag_jtag_TDO_data;	// @[ChipTop.scala:28:35]
  wire _system_debug_dmactive;	// @[ChipTop.scala:28:35]
  wire _system_uart_0_txd;	// @[ChipTop.scala:28:35]
  DigitalTop system (	// @[ChipTop.scala:28:35]
    .clock                                                                     (_system_auto_implicitClockGrouper_out_clock),	// @[ChipTop.scala:28:35]
    .reset                                                                     (_system_auto_implicitClockGrouper_out_reset),	// @[ChipTop.scala:28:35]
    .auto_prci_ctrl_domain_reset_setter_clock_in_member_allClocks_uncore_clock (clock_uncore_clock),
    .auto_prci_ctrl_domain_reset_setter_clock_in_member_allClocks_uncore_reset (reset_io),
    .resetctrl_hartIsInReset_0                                                 (_system_auto_subsystem_cbus_fixedClockNode_out_reset),	// @[ChipTop.scala:28:35]
    .debug_clock                                                               (_system_auto_subsystem_cbus_fixedClockNode_out_clock),	// @[ChipTop.scala:28:35]
    .debug_reset                                                               (~_debug_reset_syncd_debug_reset_sync_io_q),	// @[Periphery.scala:287:40, ShiftReg.scala:45:23]
    .debug_systemjtag_jtag_TCK                                                 (_iocell_jtag_TCK_i),	// @[IOCell.scala:111:23]
    .debug_systemjtag_jtag_TMS                                                 (_iocell_jtag_TMS_i),	// @[IOCell.scala:111:23]
    .debug_systemjtag_jtag_TDI                                                 (_iocell_jtag_TDI_i),	// @[IOCell.scala:111:23]
    .debug_systemjtag_reset                                                    (_system_debug_systemjtag_reset_catcher_io_sync_reset),	// @[ResetCatchAndSync.scala:39:28]
    .debug_dmactiveAck                                                         (_dmactiveAck_dmactiveAck_io_q),	// @[ShiftReg.scala:45:23]
    .mem_tl_0_a_ready                                                          (tl_slave_0_a_ready),
    .mem_tl_0_d_valid                                                          (tl_slave_0_d_valid),
    .mem_tl_0_d_bits_opcode                                                    (tl_slave_0_d_bits_opcode),
    .mem_tl_0_d_bits_param                                                     (tl_slave_0_d_bits_param),
    .mem_tl_0_d_bits_size                                                      (tl_slave_0_d_bits_size),
    .mem_tl_0_d_bits_source                                                    (tl_slave_0_d_bits_source),
    .mem_tl_0_d_bits_sink                                                      (tl_slave_0_d_bits_sink),
    .mem_tl_0_d_bits_denied                                                    (tl_slave_0_d_bits_denied),
    .mem_tl_0_d_bits_data                                                      (tl_slave_0_d_bits_data),
    .mem_tl_0_d_bits_corrupt                                                   (tl_slave_0_d_bits_corrupt),
    .custom_boot                                                               (_iocell_custom_boot_i),	// @[IOCell.scala:111:23]
    .uart_0_rxd                                                                (_iocell_uart_0_rxd_i),	// @[IOCell.scala:111:23]
    .auto_implicitClockGrouper_out_clock                                       (_system_auto_implicitClockGrouper_out_clock),
    .auto_implicitClockGrouper_out_reset                                       (_system_auto_implicitClockGrouper_out_reset),
    .auto_subsystem_cbus_fixedClockNode_out_clock                              (_system_auto_subsystem_cbus_fixedClockNode_out_clock),
    .auto_subsystem_cbus_fixedClockNode_out_reset                              (_system_auto_subsystem_cbus_fixedClockNode_out_reset),
    .debug_systemjtag_jtag_TDO_data                                            (_system_debug_systemjtag_jtag_TDO_data),
    .debug_dmactive                                                            (_system_debug_dmactive),
    .mem_tl_0_a_valid                                                          (tl_slave_0_a_valid),
    .mem_tl_0_a_bits_opcode                                                    (tl_slave_0_a_bits_opcode),
    .mem_tl_0_a_bits_param                                                     (tl_slave_0_a_bits_param),
    .mem_tl_0_a_bits_size                                                      (tl_slave_0_a_bits_size),
    .mem_tl_0_a_bits_source                                                    (tl_slave_0_a_bits_source),
    .mem_tl_0_a_bits_address                                                   (tl_slave_0_a_bits_address),
    .mem_tl_0_a_bits_mask                                                      (tl_slave_0_a_bits_mask),
    .mem_tl_0_a_bits_data                                                      (tl_slave_0_a_bits_data),
    .mem_tl_0_a_bits_corrupt                                                   (tl_slave_0_a_bits_corrupt),
    .mem_tl_0_d_ready                                                          (tl_slave_0_d_ready),
    .uart_0_txd                                                                (_system_uart_0_txd)
  );
  GenericDigitalInIOCell iocell_custom_boot (	// @[IOCell.scala:111:23]
    .pad (custom_boot),
    .ie  (1'h1),	// @[IOCell.scala:220:30]
    .i   (_iocell_custom_boot_i)
  );
  ResetCatchAndSync_d3 system_debug_systemjtag_reset_catcher (	// @[ResetCatchAndSync.scala:39:28]
    .clock         (_iocell_jtag_TCK_i),	// @[IOCell.scala:111:23]
    .reset         (_system_auto_subsystem_cbus_fixedClockNode_out_reset),	// @[ChipTop.scala:28:35]
    .io_sync_reset (_system_debug_systemjtag_reset_catcher_io_sync_reset)
  );
  AsyncResetSynchronizerShiftReg_w1_d3_i0 debug_reset_syncd_debug_reset_sync (	// @[ShiftReg.scala:45:23]
    .clock (_system_auto_subsystem_cbus_fixedClockNode_out_clock),	// @[ChipTop.scala:28:35]
    .reset (_system_debug_systemjtag_reset_catcher_io_sync_reset),	// @[ResetCatchAndSync.scala:39:28]
    .io_d  (1'h1),	// @[IOCell.scala:220:30]
    .io_q  (_debug_reset_syncd_debug_reset_sync_io_q)
  );
  ResetSynchronizerShiftReg_w1_d3_i0 dmactiveAck_dmactiveAck (	// @[ShiftReg.scala:45:23]
    .clock (_system_auto_subsystem_cbus_fixedClockNode_out_clock),	// @[ChipTop.scala:28:35]
    .reset (~_debug_reset_syncd_debug_reset_sync_io_q),	// @[Periphery.scala:287:40, ShiftReg.scala:45:23]
    .io_d  (_system_debug_dmactive),	// @[ChipTop.scala:28:35]
    .io_q  (_dmactiveAck_dmactiveAck_io_q)
  );
  GenericDigitalOutIOCell iocell_jtag_TDO (	// @[IOCell.scala:112:24]
    .o   (_system_debug_systemjtag_jtag_TDO_data),	// @[ChipTop.scala:28:35]
    .oe  (1'h1),	// @[IOCell.scala:220:30]
    .pad (jtag_TDO)
  );
  GenericDigitalInIOCell iocell_jtag_TDI (	// @[IOCell.scala:111:23]
    .pad (jtag_TDI),
    .ie  (1'h1),	// @[IOCell.scala:220:30]
    .i   (_iocell_jtag_TDI_i)
  );
  GenericDigitalInIOCell iocell_jtag_TMS (	// @[IOCell.scala:111:23]
    .pad (jtag_TMS),
    .ie  (1'h1),	// @[IOCell.scala:220:30]
    .i   (_iocell_jtag_TMS_i)
  );
  GenericDigitalInIOCell iocell_jtag_TCK (	// @[IOCell.scala:111:23]
    .pad (jtag_TCK),
    .ie  (1'h1),	// @[IOCell.scala:220:30]
    .i   (_iocell_jtag_TCK_i)
  );
  GenericDigitalInIOCell iocell_uart_0_rxd (	// @[IOCell.scala:111:23]
    .pad (uart_0_rxd),
    .ie  (1'h1),	// @[IOCell.scala:220:30]
    .i   (_iocell_uart_0_rxd_i)
  );
  GenericDigitalOutIOCell iocell_uart_0_txd (	// @[IOCell.scala:112:24]
    .o   (_system_uart_0_txd),	// @[ChipTop.scala:28:35]
    .oe  (1'h1),	// @[IOCell.scala:220:30]
    .pad (uart_0_txd)
  );
endmodule

