# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/binhkieudo/Workspace/RISC-V/NewFramework/framework/usb/project/project.srcs/sources_1/ip/harnessSysPLL/harnessSysPLL.xci
# IP: The module: 'harnessSysPLL' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/binhkieudo/Workspace/RISC-V/NewFramework/framework/usb/project/project.gen/sources_1/ip/harnessSysPLL/harnessSysPLL_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'harnessSysPLL'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/binhkieudo/Workspace/RISC-V/NewFramework/framework/usb/project/project.gen/sources_1/ip/harnessSysPLL/harnessSysPLL.xdc
# XDC: The top module name and the constraint reference have the same name: 'harnessSysPLL'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/binhkieudo/Workspace/RISC-V/NewFramework/framework/usb/project/project.gen/sources_1/ip/harnessSysPLL/harnessSysPLL_late.xdc
# XDC: The top module name and the constraint reference have the same name: 'harnessSysPLL'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/binhkieudo/Workspace/RISC-V/NewFramework/framework/usb/project/project.gen/sources_1/ip/harnessSysPLL/harnessSysPLL_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'harnessSysPLL'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/binhkieudo/Workspace/RISC-V/NewFramework/framework/usb/project/project.srcs/sources_1/ip/harnessSysPLL/harnessSysPLL.xci
# IP: The module: 'harnessSysPLL' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/binhkieudo/Workspace/RISC-V/NewFramework/framework/usb/project/project.gen/sources_1/ip/harnessSysPLL/harnessSysPLL_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'harnessSysPLL'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/binhkieudo/Workspace/RISC-V/NewFramework/framework/usb/project/project.gen/sources_1/ip/harnessSysPLL/harnessSysPLL.xdc
# XDC: The top module name and the constraint reference have the same name: 'harnessSysPLL'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/binhkieudo/Workspace/RISC-V/NewFramework/framework/usb/project/project.gen/sources_1/ip/harnessSysPLL/harnessSysPLL_late.xdc
# XDC: The top module name and the constraint reference have the same name: 'harnessSysPLL'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/binhkieudo/Workspace/RISC-V/NewFramework/framework/usb/project/project.gen/sources_1/ip/harnessSysPLL/harnessSysPLL_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'harnessSysPLL'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
