// Generated by CIRCT unknown git version
// Standard header to adapt well known macros to our needs.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

module Arty100THarness(
  input         sys_clock,
  inout         uart_txd,
                uart_rxd,
  inout  [15:0] ddr_ddr3_dq,
  inout  [1:0]  ddr_ddr3_dqs_n,
                ddr_ddr3_dqs_p,
  inout         jtag_jtag_TCK,
                jtag_jtag_TMS,
                jtag_jtag_TDI,
                jtag_jtag_TDO,
                jtag_srst_n,
  input         reset,
  output [13:0] ddr_ddr3_addr,
  output [2:0]  ddr_ddr3_ba,
  output        ddr_ddr3_ras_n,
                ddr_ddr3_cas_n,
                ddr_ddr3_we_n,
                ddr_ddr3_reset_n,
                ddr_ddr3_ck_p,
                ddr_ddr3_ck_n,
                ddr_ddr3_cke,
                ddr_ddr3_cs_n,
  output [1:0]  ddr_ddr3_dm,
  output        ddr_ddr3_odt,
                led_status_0,
                led_status_1,
                led_status_2
);

  wire        _harnessBinderReset_catcher_io_sync_reset;	// @[ResetCatchAndSync.scala:39:28]
  wire        _plusarg_reader_out;	// @[PlusArg.scala:80:11]
  wire        _chiptop0_tl_slave_0_a_valid;	// @[HasHarnessInstantiators.scala:82:40]
  wire [2:0]  _chiptop0_tl_slave_0_a_bits_opcode;	// @[HasHarnessInstantiators.scala:82:40]
  wire [2:0]  _chiptop0_tl_slave_0_a_bits_param;	// @[HasHarnessInstantiators.scala:82:40]
  wire [2:0]  _chiptop0_tl_slave_0_a_bits_size;	// @[HasHarnessInstantiators.scala:82:40]
  wire [3:0]  _chiptop0_tl_slave_0_a_bits_source;	// @[HasHarnessInstantiators.scala:82:40]
  wire [31:0] _chiptop0_tl_slave_0_a_bits_address;	// @[HasHarnessInstantiators.scala:82:40]
  wire [7:0]  _chiptop0_tl_slave_0_a_bits_mask;	// @[HasHarnessInstantiators.scala:82:40]
  wire [63:0] _chiptop0_tl_slave_0_a_bits_data;	// @[HasHarnessInstantiators.scala:82:40]
  wire        _chiptop0_tl_slave_0_a_bits_corrupt;	// @[HasHarnessInstantiators.scala:82:40]
  wire        _chiptop0_tl_slave_0_d_ready;	// @[HasHarnessInstantiators.scala:82:40]
  wire        _chiptop0_jtag_TDO;	// @[HasHarnessInstantiators.scala:82:40]
  wire        _chiptop0_uart_0_txd;	// @[HasHarnessInstantiators.scala:82:40]
  wire        _fpga_power_on_power_on_reset;	// @[Xilinx.scala:104:21]
  wire        _reset_ibuf_O;	// @[CustomShell.scala:39:28]
  wire        _bundleIn_0_srst_n_a2b_b;	// @[Util.scala:30:21]
  wire        _bundleIn_0_TDI_a2b_b;	// @[Util.scala:30:21]
  wire        _bundleIn_0_TMS_a2b_b;	// @[Util.scala:30:21]
  wire        _bundleIn_0_TCK_a2b_b;	// @[Util.scala:30:21]
  wire        _bundleIn_0_rxd_a2b_b;	// @[Util.scala:30:21]
  wire        _sys_clock_ibufg_O;	// @[ClockOverlay.scala:32:22]
  wire        _harnessSysPLLNode_clk_out1;	// @[XilinxShell.scala:76:55]
  wire        _harnessSysPLLNode_clk_out2;	// @[XilinxShell.scala:76:55]
  wire        _harnessSysPLLNode_clk_out3;	// @[XilinxShell.scala:76:55]
  wire        _harnessSysPLLNode_locked;	// @[XilinxShell.scala:76:55]
  wire        _mig_auto_buffer_in_a_ready;	// @[CustomOverlay.scala:46:23]
  wire        _mig_auto_buffer_in_d_valid;	// @[CustomOverlay.scala:46:23]
  wire [2:0]  _mig_auto_buffer_in_d_bits_opcode;	// @[CustomOverlay.scala:46:23]
  wire [1:0]  _mig_auto_buffer_in_d_bits_param;	// @[CustomOverlay.scala:46:23]
  wire [2:0]  _mig_auto_buffer_in_d_bits_size;	// @[CustomOverlay.scala:46:23]
  wire [3:0]  _mig_auto_buffer_in_d_bits_source;	// @[CustomOverlay.scala:46:23]
  wire        _mig_auto_buffer_in_d_bits_sink;	// @[CustomOverlay.scala:46:23]
  wire        _mig_auto_buffer_in_d_bits_denied;	// @[CustomOverlay.scala:46:23]
  wire [63:0] _mig_auto_buffer_in_d_bits_data;	// @[CustomOverlay.scala:46:23]
  wire        _mig_auto_buffer_in_d_bits_corrupt;	// @[CustomOverlay.scala:46:23]
  wire        _mig_io_port_ui_clk;	// @[CustomOverlay.scala:46:23]
  wire        _mig_io_port_ui_clk_sync_rst;	// @[CustomOverlay.scala:46:23]
  wire        _mig_io_port_mmcm_locked;	// @[CustomOverlay.scala:46:23]
  wire        _mig_io_port_init_calib_complete;	// @[CustomOverlay.scala:46:23]
  wire        _ddrGroup_auto_out_1_clock;	// @[ClockGroup.scala:31:15]
  wire        _ddrGroup_auto_out_1_reset;	// @[ClockGroup.scala:31:15]
  wire        _ddrGroup_auto_out_0_clock;	// @[ClockGroup.scala:31:15]
  wire        _ddrGroup_auto_out_0_reset;	// @[ClockGroup.scala:31:15]
  wire        _dutGroup_auto_out_clock;	// @[ClockGroup.scala:31:15]
  wire        _dutGroup_auto_out_reset;	// @[ClockGroup.scala:31:15]
  wire        _dutWrangler_auto_out_3_reset;	// @[Harness.scala:26:31]
  wire        _dutWrangler_auto_out_2_clock;	// @[Harness.scala:26:31]
  wire        _dutWrangler_auto_out_1_clock;	// @[Harness.scala:26:31]
  wire        _dutWrangler_auto_out_0_clock;	// @[Harness.scala:26:31]
  wire        _dutWrangler_auto_out_0_reset;	// @[Harness.scala:26:31]
  reg  [1:0]  ddrBlockDuringReset_c_value;	// @[Counter.scala:61:40]
  reg         ddrBlockDuringReset_r;	// @[Reg.scala:35:20]
  reg  [1:0]  ddrBlockDuringReset_c_value_1;	// @[Counter.scala:61:40]
  reg         ddrBlockDuringReset_r_1;	// @[Reg.scala:35:20]
  wire        _WIRE_1 = ~_reset_ibuf_O | _fpga_power_on_power_on_reset;	// @[CustomShell.scala:39:28, :51:{8,26}, Xilinx.scala:104:21]
  reg  [25:0] REG;	// @[Harness.scala:62:28]
  reg         REG_1;	// @[Harness.scala:63:23]
  always @(posedge _dutWrangler_auto_out_0_clock) begin	// @[Harness.scala:26:31]
    if (_harnessBinderReset_catcher_io_sync_reset | ~_mig_io_port_init_calib_complete) begin	// @[CustomOverlay.scala:46:23, Harness.scala:26:31, :83:{67,70}, ResetCatchAndSync.scala:39:28]
      ddrBlockDuringReset_c_value <= 2'h0;	// @[Counter.scala:61:40]
      ddrBlockDuringReset_r <= 1'h0;	// @[LazyModule.scala:411:29, Reg.scala:35:20]
      ddrBlockDuringReset_c_value_1 <= 2'h0;	// @[Counter.scala:61:40]
      ddrBlockDuringReset_r_1 <= 1'h0;	// @[LazyModule.scala:411:29, Reg.scala:35:20]
    end
    else begin	// @[Harness.scala:26:31]
      ddrBlockDuringReset_c_value <= ddrBlockDuringReset_c_value + 2'h1;	// @[Counter.scala:61:40, :77:24]
      ddrBlockDuringReset_r <= (&ddrBlockDuringReset_c_value) | ddrBlockDuringReset_r;	// @[Counter.scala:61:40, :73:24, Reg.scala:35:20, :36:{18,22}]
      ddrBlockDuringReset_c_value_1 <= ddrBlockDuringReset_c_value_1 + 2'h1;	// @[Counter.scala:61:40, :77:24]
      ddrBlockDuringReset_r_1 <= (&ddrBlockDuringReset_c_value_1) | ddrBlockDuringReset_r_1;	// @[Counter.scala:61:40, :73:24, Reg.scala:35:20, :36:{18,22}]
    end
  end // always @(posedge)
  always @(posedge _sys_clock_ibufg_O) begin	// @[ClockOverlay.scala:32:22]
    if (_dutWrangler_auto_out_0_reset) begin	// @[ClockOverlay.scala:32:22, Harness.scala:26:31]
      REG <= 26'h0;	// @[Harness.scala:62:28]
      REG_1 <= 1'h0;	// @[Harness.scala:63:23, LazyModule.scala:411:29]
    end
    else begin	// @[ClockOverlay.scala:32:22]
      if (REG == 26'h31FFFFF)	// @[Harness.scala:62:28, :64:30]
        REG <= 26'h0;	// @[Harness.scala:62:28]
      else	// @[Harness.scala:64:30]
        REG <= REG + 26'h1;	// @[Harness.scala:62:28, :64:61]
      REG_1 <= REG == 26'h0 ^ REG_1;	// @[Harness.scala:62:28, :63:23, :65:{21,30}, :66:12]
    end
  end // always @(posedge)
  `ifndef SYNTHESIS
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM_0;
    logic [31:0] _RANDOM_1;
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        _RANDOM_0 = `RANDOM;
        _RANDOM_1 = `RANDOM;
        ddrBlockDuringReset_c_value = _RANDOM_0[1:0];	// @[Counter.scala:61:40]
        ddrBlockDuringReset_r = _RANDOM_0[2];	// @[Counter.scala:61:40, Reg.scala:35:20]
        ddrBlockDuringReset_c_value_1 = _RANDOM_0[4:3];	// @[Counter.scala:61:40]
        ddrBlockDuringReset_r_1 = _RANDOM_0[5];	// @[Counter.scala:61:40, Reg.scala:35:20]
        REG = _RANDOM_0[31:6];	// @[Counter.scala:61:40, Harness.scala:62:28]
        REG_1 = _RANDOM_1[0];	// @[Harness.scala:63:23]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // not def SYNTHESIS
  ResetWrangler dutWrangler (	// @[Harness.scala:26:31]
    .auto_in_3_clock  (_mig_io_port_ui_clk),	// @[CustomOverlay.scala:46:23]
    .auto_in_3_reset  (~_mig_io_port_mmcm_locked | _mig_io_port_ui_clk_sync_rst),	// @[CustomOverlay.scala:46:23, :69:{17,35}]
    .auto_in_2_clock  (_ddrGroup_auto_out_1_clock),	// @[ClockGroup.scala:31:15]
    .auto_in_2_reset  (_ddrGroup_auto_out_1_reset),	// @[ClockGroup.scala:31:15]
    .auto_in_1_clock  (_ddrGroup_auto_out_0_clock),	// @[ClockGroup.scala:31:15]
    .auto_in_1_reset  (_ddrGroup_auto_out_0_reset),	// @[ClockGroup.scala:31:15]
    .auto_in_0_clock  (_dutGroup_auto_out_clock),	// @[ClockGroup.scala:31:15]
    .auto_in_0_reset  (_dutGroup_auto_out_reset),	// @[ClockGroup.scala:31:15]
    .auto_out_3_reset (_dutWrangler_auto_out_3_reset),
    .auto_out_2_clock (_dutWrangler_auto_out_2_clock),
    .auto_out_1_clock (_dutWrangler_auto_out_1_clock),
    .auto_out_0_clock (_dutWrangler_auto_out_0_clock),
    .auto_out_0_reset (_dutWrangler_auto_out_0_reset)
  );
  ClockGroup dutGroup (	// @[ClockGroup.scala:31:15]
    .auto_in_member_0_clock (_harnessSysPLLNode_clk_out1),	// @[XilinxShell.scala:76:55]
    .auto_in_member_0_reset (~_harnessSysPLLNode_locked | ~_reset_ibuf_O),	// @[CustomShell.scala:39:28, Harness.scala:55:56, PLLFactory.scala:78:{20,35}, XilinxShell.scala:76:55]
    .auto_out_clock         (_dutGroup_auto_out_clock),
    .auto_out_reset         (_dutGroup_auto_out_reset)
  );
  ClockGroup_1 ddrGroup (	// @[ClockGroup.scala:31:15]
    .auto_in_member_1_clock (_harnessSysPLLNode_clk_out3),	// @[XilinxShell.scala:76:55]
    .auto_in_member_1_reset (~_harnessSysPLLNode_locked | ~_reset_ibuf_O),	// @[CustomShell.scala:39:28, Harness.scala:55:56, PLLFactory.scala:78:{20,35}, XilinxShell.scala:76:55]
    .auto_in_member_0_clock (_harnessSysPLLNode_clk_out2),	// @[XilinxShell.scala:76:55]
    .auto_in_member_0_reset (~_harnessSysPLLNode_locked | ~_reset_ibuf_O),	// @[CustomShell.scala:39:28, Harness.scala:55:56, PLLFactory.scala:78:{20,35}, XilinxShell.scala:76:55]
    .auto_out_1_clock       (_ddrGroup_auto_out_1_clock),
    .auto_out_1_reset       (_ddrGroup_auto_out_1_reset),
    .auto_out_0_clock       (_ddrGroup_auto_out_0_clock),
    .auto_out_0_reset       (_ddrGroup_auto_out_0_reset)
  );
  XilinxArty100TMIG mig (	// @[CustomOverlay.scala:46:23]
    .clock                         (_dutWrangler_auto_out_0_clock),	// @[Harness.scala:26:31]
    .reset                         (_harnessBinderReset_catcher_io_sync_reset),	// @[ResetCatchAndSync.scala:39:28]
    .auto_buffer_in_a_valid        (ddrBlockDuringReset_r & _chiptop0_tl_slave_0_a_valid),	// @[Blockable.scala:34:18, :37:30, :38:20, HasHarnessInstantiators.scala:82:40, Reg.scala:35:20]
    .auto_buffer_in_a_bits_opcode  (_chiptop0_tl_slave_0_a_bits_opcode),	// @[HasHarnessInstantiators.scala:82:40]
    .auto_buffer_in_a_bits_param   (_chiptop0_tl_slave_0_a_bits_param),	// @[HasHarnessInstantiators.scala:82:40]
    .auto_buffer_in_a_bits_size    (_chiptop0_tl_slave_0_a_bits_size),	// @[HasHarnessInstantiators.scala:82:40]
    .auto_buffer_in_a_bits_source  (_chiptop0_tl_slave_0_a_bits_source),	// @[HasHarnessInstantiators.scala:82:40]
    .auto_buffer_in_a_bits_address (_chiptop0_tl_slave_0_a_bits_address),	// @[HasHarnessInstantiators.scala:82:40]
    .auto_buffer_in_a_bits_mask    (_chiptop0_tl_slave_0_a_bits_mask),	// @[HasHarnessInstantiators.scala:82:40]
    .auto_buffer_in_a_bits_data    (_chiptop0_tl_slave_0_a_bits_data),	// @[HasHarnessInstantiators.scala:82:40]
    .auto_buffer_in_a_bits_corrupt (_chiptop0_tl_slave_0_a_bits_corrupt),	// @[HasHarnessInstantiators.scala:82:40]
    .auto_buffer_in_d_ready        (ddrBlockDuringReset_r_1 & _chiptop0_tl_slave_0_d_ready),	// @[Blockable.scala:35:18, :37:30, :39:20, HasHarnessInstantiators.scala:82:40, Reg.scala:35:20]
    .io_port_ddr3_dq               (ddr_ddr3_dq),
    .io_port_ddr3_dqs_n            (ddr_ddr3_dqs_n),
    .io_port_ddr3_dqs_p            (ddr_ddr3_dqs_p),
    .io_port_sys_clk_i             (_dutWrangler_auto_out_1_clock),	// @[Harness.scala:26:31]
    .io_port_clk_ref_i             (_dutWrangler_auto_out_2_clock),	// @[Harness.scala:26:31]
    .io_port_aresetn               (~_dutWrangler_auto_out_3_reset),	// @[CustomOverlay.scala:73:21, Harness.scala:26:31]
    .io_port_sys_rst               (_WIRE_1),	// @[CustomShell.scala:51:26]
    .auto_buffer_in_a_ready        (_mig_auto_buffer_in_a_ready),
    .auto_buffer_in_d_valid        (_mig_auto_buffer_in_d_valid),
    .auto_buffer_in_d_bits_opcode  (_mig_auto_buffer_in_d_bits_opcode),
    .auto_buffer_in_d_bits_param   (_mig_auto_buffer_in_d_bits_param),
    .auto_buffer_in_d_bits_size    (_mig_auto_buffer_in_d_bits_size),
    .auto_buffer_in_d_bits_source  (_mig_auto_buffer_in_d_bits_source),
    .auto_buffer_in_d_bits_sink    (_mig_auto_buffer_in_d_bits_sink),
    .auto_buffer_in_d_bits_denied  (_mig_auto_buffer_in_d_bits_denied),
    .auto_buffer_in_d_bits_data    (_mig_auto_buffer_in_d_bits_data),
    .auto_buffer_in_d_bits_corrupt (_mig_auto_buffer_in_d_bits_corrupt),
    .io_port_ddr3_addr             (ddr_ddr3_addr),
    .io_port_ddr3_ba               (ddr_ddr3_ba),
    .io_port_ddr3_ras_n            (ddr_ddr3_ras_n),
    .io_port_ddr3_cas_n            (ddr_ddr3_cas_n),
    .io_port_ddr3_we_n             (ddr_ddr3_we_n),
    .io_port_ddr3_reset_n          (ddr_ddr3_reset_n),
    .io_port_ddr3_ck_p             (ddr_ddr3_ck_p),
    .io_port_ddr3_ck_n             (ddr_ddr3_ck_n),
    .io_port_ddr3_cke              (ddr_ddr3_cke),
    .io_port_ddr3_cs_n             (ddr_ddr3_cs_n),
    .io_port_ddr3_dm               (ddr_ddr3_dm),
    .io_port_ddr3_odt              (ddr_ddr3_odt),
    .io_port_ui_clk                (_mig_io_port_ui_clk),
    .io_port_ui_clk_sync_rst       (_mig_io_port_ui_clk_sync_rst),
    .io_port_mmcm_locked           (_mig_io_port_mmcm_locked),
    .io_port_init_calib_complete   (_mig_io_port_init_calib_complete)
  );
  harnessSysPLLNode harnessSysPLLNode (	// @[XilinxShell.scala:76:55]
    .clk_in1  (_sys_clock_ibufg_O),	// @[ClockOverlay.scala:32:22]
    .reset    (_WIRE_1),	// @[CustomShell.scala:51:26]
    .clk_out1 (_harnessSysPLLNode_clk_out1),
    .clk_out2 (_harnessSysPLLNode_clk_out2),
    .clk_out3 (_harnessSysPLLNode_clk_out3),
    .locked   (_harnessSysPLLNode_locked)
  );
  IBUFG sys_clock_ibufg (	// @[ClockOverlay.scala:32:22]
    .I (sys_clock),
    .O (_sys_clock_ibufg_O)
  );
  UIntToAnalog_1 a2b (	// @[Util.scala:58:21]
    .a    (uart_txd),
    .b    (_chiptop0_uart_0_txd),	// @[HasHarnessInstantiators.scala:82:40]
    .b_en (1'h1)	// @[Counter.scala:118:16]
  );
  AnalogToUInt_1 bundleIn_0_rxd_a2b (	// @[Util.scala:30:21]
    .a (uart_rxd),
    .b (_bundleIn_0_rxd_a2b_b)
  );
  AnalogToUInt_1 bundleIn_0_TCK_a2b (	// @[Util.scala:30:21]
    .a (jtag_jtag_TCK),
    .b (_bundleIn_0_TCK_a2b_b)
  );
  AnalogToUInt_1 bundleIn_0_TMS_a2b (	// @[Util.scala:30:21]
    .a (jtag_jtag_TMS),
    .b (_bundleIn_0_TMS_a2b_b)
  );
  AnalogToUInt_1 bundleIn_0_TDI_a2b (	// @[Util.scala:30:21]
    .a (jtag_jtag_TDI),
    .b (_bundleIn_0_TDI_a2b_b)
  );
  UIntToAnalog_1 a2b_1 (	// @[Util.scala:58:21]
    .a    (jtag_jtag_TDO),
    .b    (_chiptop0_jtag_TDO),	// @[HasHarnessInstantiators.scala:82:40]
    .b_en (1'h1)	// @[Counter.scala:118:16]
  );
  AnalogToUInt_1 bundleIn_0_srst_n_a2b (	// @[Util.scala:30:21]
    .a (jtag_srst_n),
    .b (_bundleIn_0_srst_n_a2b_b)
  );
  IBUF reset_ibuf (	// @[CustomShell.scala:39:28]
    .I (reset),
    .O (_reset_ibuf_O)
  );
  PowerOnResetFPGAOnly fpga_power_on (	// @[Xilinx.scala:104:21]
    .clock          (_sys_clock_ibufg_O),	// @[ClockOverlay.scala:32:22]
    .power_on_reset (_fpga_power_on_power_on_reset)
  );
  ChipTop chiptop0 (	// @[HasHarnessInstantiators.scala:82:40]
    .tl_slave_0_a_ready        (ddrBlockDuringReset_r & _mig_auto_buffer_in_a_ready),	// @[Blockable.scala:35:18, :37:30, :39:20, CustomOverlay.scala:46:23, Reg.scala:35:20]
    .tl_slave_0_d_valid        (ddrBlockDuringReset_r_1 & _mig_auto_buffer_in_d_valid),	// @[Blockable.scala:34:18, :37:30, :38:20, CustomOverlay.scala:46:23, Reg.scala:35:20]
    .tl_slave_0_d_bits_opcode  (_mig_auto_buffer_in_d_bits_opcode),	// @[CustomOverlay.scala:46:23]
    .tl_slave_0_d_bits_param   (_mig_auto_buffer_in_d_bits_param),	// @[CustomOverlay.scala:46:23]
    .tl_slave_0_d_bits_size    (_mig_auto_buffer_in_d_bits_size),	// @[CustomOverlay.scala:46:23]
    .tl_slave_0_d_bits_source  (_mig_auto_buffer_in_d_bits_source),	// @[CustomOverlay.scala:46:23]
    .tl_slave_0_d_bits_sink    (_mig_auto_buffer_in_d_bits_sink),	// @[CustomOverlay.scala:46:23]
    .tl_slave_0_d_bits_denied  (_mig_auto_buffer_in_d_bits_denied),	// @[CustomOverlay.scala:46:23]
    .tl_slave_0_d_bits_data    (_mig_auto_buffer_in_d_bits_data),	// @[CustomOverlay.scala:46:23]
    .tl_slave_0_d_bits_corrupt (_mig_auto_buffer_in_d_bits_corrupt),	// @[CustomOverlay.scala:46:23]
    .custom_boot               (_plusarg_reader_out),	// @[PlusArg.scala:80:11]
    .reset_io                  (_harnessBinderReset_catcher_io_sync_reset),	// @[ResetCatchAndSync.scala:39:28]
    .clock_uncore_clock        (_dutWrangler_auto_out_0_clock),	// @[Harness.scala:26:31]
    .jtag_TCK                  (_bundleIn_0_TCK_a2b_b),	// @[Util.scala:30:21]
    .jtag_TMS                  (_bundleIn_0_TMS_a2b_b),	// @[Util.scala:30:21]
    .jtag_TDI                  (_bundleIn_0_TDI_a2b_b),	// @[Util.scala:30:21]
    .uart_0_rxd                (_bundleIn_0_rxd_a2b_b),	// @[Util.scala:30:21]
    .tl_slave_0_a_valid        (_chiptop0_tl_slave_0_a_valid),
    .tl_slave_0_a_bits_opcode  (_chiptop0_tl_slave_0_a_bits_opcode),
    .tl_slave_0_a_bits_param   (_chiptop0_tl_slave_0_a_bits_param),
    .tl_slave_0_a_bits_size    (_chiptop0_tl_slave_0_a_bits_size),
    .tl_slave_0_a_bits_source  (_chiptop0_tl_slave_0_a_bits_source),
    .tl_slave_0_a_bits_address (_chiptop0_tl_slave_0_a_bits_address),
    .tl_slave_0_a_bits_mask    (_chiptop0_tl_slave_0_a_bits_mask),
    .tl_slave_0_a_bits_data    (_chiptop0_tl_slave_0_a_bits_data),
    .tl_slave_0_a_bits_corrupt (_chiptop0_tl_slave_0_a_bits_corrupt),
    .tl_slave_0_d_ready        (_chiptop0_tl_slave_0_d_ready),
    .jtag_TDO                  (_chiptop0_jtag_TDO),
    .uart_0_txd                (_chiptop0_uart_0_txd)
  );
  plusarg_reader_Arty100THarness_UNIQUIFIED #(
    .FORMAT("custom_boot_pin=%d"),
    .DEFAULT(0),
    .WIDTH(1)
  ) plusarg_reader_Arty100THarness_UNIQUIFIED (	// @[PlusArg.scala:80:11]
    .out (_plusarg_reader_out)
  );
  ResetCatchAndSync_d3_Arty100THarness_UNIQUIFIED harnessBinderReset_catcher (	// @[ResetCatchAndSync.scala:39:28]
    .clock         (_dutWrangler_auto_out_0_clock),	// @[Harness.scala:26:31]
    .reset         (_dutWrangler_auto_out_0_reset),	// @[Harness.scala:26:31]
    .io_sync_reset (_harnessBinderReset_catcher_io_sync_reset)
  );
  assign led_status_0 = _reset_ibuf_O;	// @[CustomShell.scala:39:28]
  assign led_status_1 = _mig_io_port_init_calib_complete;	// @[CustomOverlay.scala:46:23]
  assign led_status_2 = REG_1;	// @[Harness.scala:63:23]
endmodule

